# -*- coding: utf-8 -*-
import re

def normalize_cms_AR(newName):
      # print('state to be normalized: ', state)
      print('passed in facility name: ', newName)
      
      # AR
      # ENCORE HEALTHCARE AND REHABILITATION OF WEST LITTL -> ENCORE HEALTHCARE AND REHABILITATION OF WEST LITTLE ROCK
      # ??? MIDTOWN POST ACUTE AND REHABILITATION - A WATERS C
      # ??? THE MAPLES AT HAR-BER MEADOWS
      newName = re.sub('ALMA HEALTHCARE AND REHABILITATION CENTER', 'ALMA HEALTH AND REHABILITATION CENTER', newName)
      newName = re.sub('ARKANSAS STATE VETERANS HOME AT NORTH LITTLE ROCK', 'ARKANSAS STATE VETERANS HOME-NORTH LITTLE ROCK', newName)
      newName = re.sub('ASHLEY REHABILITATION AND HEALTH CARE CENTER', 'ASHLEY HEALTH AND REHABILITATION', newName)
      newName = re.sub('AUTUMN HILL', 'AUTUMN HILL THERAPY AND LIVING CENTER', newName)
      newName = re.sub('BUTTERFIELD TRAIL VILLAGE', 'BUTTERFIELD TRAILS VILLAGE NURSING HOME', newName)
      newName = re.sub('BENTLEY REHABILITATION AND HEALTH CENTER', 'BENTLEY REHABILITATION AND HEALTHCARE', newName)
      newName = re.sub('CRESTPARK DEWITT', 'CRESTPARK OF DEWITT', newName)
      newName = re.sub('CRESTPARK FORREST CITY', 'CRESTPARK OF FORREST CITY', newName)
      newName = re.sub('CRESTPARK HELENA', 'CRESTPARK OF HELENA', newName)

      newName = re.sub('CRESTPARK STUTTGART', 'CRESTPARK OF STUTTGART', newName)
      newName = re.sub('CRESTPARK WYNNE', 'CRESTPARK OF WYNNE', newName)
      newName = re.sub('DARDANELLE NURSING AND REHABILITATION CENTER', 'D ARDANELLE NURSING AND REHABILITATION CENTER', newName)
      newName = re.sub('DIERKS HEALTH AND REHABILITATION', 'DIERKS HEALTH AND REHABILITATION CENTER', newName)
      # newName = re.sub('HIGHLAND COURT, A REHABILITATION AND RESIDENT CARE', 'HIGHLAND COURT A REHABILITATION AND RESIDENT CARE FACILITY', newName)
      newName = re.sub('LAKESIDE HEALTH AND REHABILITATION', 'LAKESIDE NURSING CENTER', newName)
      # newName = re.sub('MOUNTAIN MEADOWS HEALTH AND REHABILITATION', 'MOUNTAIN MEADOWS NURSING AND REHABILITATION', newName)

      newName = re.sub('MIDTOWN POST ACUTE AND REHABILITATION - A WATERS C', 'MIDTOWN POST ACUTE AND REHABILITATION - A WATERS COMMUNITY', newName)
      newName = re.sub('MONTGOMERY COUNTY NURSING HOME', 'MONTGOMERY COUNTY ASSISTED LIVING', newName)
      newName = re.sub('MOUNTAIN MEADOWS NURSING AND REHABILITATION', 'MOUNTAIN MEADOWS HEALTH AND REHABILITATION', newName)

      newName = re.sub('SEARCY HEALTHCARE', 'SEARCY HEALTHCARE/THE SPRINGS OF SEARCY', newName)
      newName = re.sub('SHERWOOD NURSING AND REHABILITATION CENTER', 'SHERWOOD NURSING AND REHABILITATION', newName)
      # newName = re.sub('SHILOH NURSING AND REHABILITATION', 'SHILOH NURSING AND REHAB-SPRINGDALE', newName)
      newName = re.sub('SILOAM HEALTHCARE', 'SILOAM HEALTHCARE/SILOAM SPRINGS NURSING AND REHABILITATION', newName)
      newName = re.sub('SOUTHERN PINES HEALTH AND REHABILITATION', 'SOUTHERN PINES NURSING AND REHAB/PRESCOTT MANOR', newName)
      newName = re.sub('SOMERSET SENIOR LIVING AT CANYON SPRINGS', 'CANYON SPRINGS HEALTH AND REHABILITATION', newName)
      newName = re.sub('SPRINGDALE HEALTH AND REHABILITATION CENTER', 'SPRINGDALE HEALTH AND REHABILITATION', newName)
      newName = re.sub('ST ANDREWS HEALTHCARE', 'ST. ANDREW\'S PLACE', newName)
      newName = re.sub('ST ELIZABETH\'S PLACE', 'ST. ELIZABETH\'S PLACE', newName)

      newName = re.sub('ST MICHAEL\'S HEALTHCARE', 'ST. MICHAEL\'S PLACE, NEWPORT HEALTHCARE AND REHABILITATION CENTER', newName)
      newName = re.sub('THE CROSSING AT RIVERSIDE HEALTH AND REHABILITATIO', 'THE CROSSING AT RIVERSIDE HEALTH AND REHABILITATION', newName)

      # newName = re.sub('TWIN RIVERS HEALTH AND REHABILITATION', 'TWIN RIVERS HEALTH AND REHAB-ARKADELPHIA', newName)
      newName = re.sub('WILLOWBEND HEALTHCARE AND REHABILITATION', 'WILLOW BEND HEALTHCARE AND REHABILITATION', newName)

      return newName