# -*- coding: utf-8 -*-
import re

def normalize_cms_NY(newName):
      # print('state to be normalized: ', state)
      print('passed in facility name: ', newName)
      # NY
      # JOHN T MATHER MEMORIAL HOSPITALTC U -> JOHN T MATHER MEMORIAL HOSPITAL TCU
      # R H C F -> RHCF
      newName = re.sub('BROOKLYN QUEENS NURSING HOME', 'BROOKLYN-QUEENS NURSING HOME', newName)
      newName = re.sub('BUENA VIDA REHABILITATION AND NURSING CENTER', 'BUENA VIDA CONTINUING CARE AND REHABILITATION CENTER', newName)
      newName = re.sub('DR SUSAN SMITH MCKINNEY NURSING AND REHABILITATION CENTER', 'DR SUSAN SMITH MCKINNEY NURSING AND REHABILITATION', newName)
      newName = re.sub('GLENGARIFF HEALTH CARE CENTER', 'GLENGARIFF REHABILITATION AND HEALTHCARE CENTER', newName)
      newName = re.sub('GOOD SAMARITAN NURSING HOME', 'GOOD SAMARITAN NURSING AND REHABILITATION CARE CENTER', newName)
      newName = re.sub('IRA DAVENPORT MEMORIAL HOSPITAL SNF/ HRF', 'IRA DAVENPORT MEMORIAL HOSPITAL SNF/HRF', newName)
      newName = re.sub('JAMES G JOHNSTON MEMORIAL NURSING HOME', 'JAMES G. JOHNSTON MEMORIAL NURSING HOME', newName)
      newName = re.sub('MARGARET TIETZ CENTER FOR NURSING CARE', 'MARGARET TIETZ NURSING AND REHABILITATION CENTER', newName)
      newName = re.sub('MEADOW PARK REHABILITATION AND HEALTH CENTER', 'MEADOW PARK REHABILITATION AND HEALTH CARE CENTER', newName)
      newName = re.sub('NORTH SHORE - L I J ORZAC CENTER FOR REHABILITATION', 'NORTH SHORE-LIJ ORZAC CENTER FOR REHABILITATION', newName)
      newName = re.sub('NORTH WESTCHESTER RESTORATIVE THERAPY AND NURSING CRT', 'NORTH WESTCHESTER RESTORATIVE THERAPY AND NURSING', newName)
      newName = re.sub('NORTHERN METROPOLITAN RES HEALTH CARE FACILITY', 'NORTHERN METROPOLITAN RESIDENTIAL HEALTH CARE FACILITY', newName)
      newName = re.sub('NORTHERN RIVERVIEW HEALTH CARE', 'NORTHERN RIVERVIEW HEALTH CARE CENTER', newName)
      newName = re.sub('NYS VETERANS HOME INNYC', 'NYS VETERANS HOME IN NYC', newName)
      newName = re.sub('OCEANVIEW NURSING AND REHABILITATION CARE CENTER', 'OCEANVIEW NURSING AND REHABILITATION CENTER', newName)
      newName = re.sub('OUR LADY OF CONSOLATION NURSING AND REHABILITATION CARE CENTER', 'OUR LADY OF CONSOLATION NURSING AND REHABILITATIVE CARE', newName)
      newName = re.sub('PELHAM PARKWAY NURSING CENTER AND REHABILITATION FACILITY', 'PELHAM PARKWAY NURSING CARE AND REHABILITATION FACILITY', newName)
      
      newName = re.sub('ROME MEMORIAL HOSPITAL - R HCF', 'ROME MEMORIAL HOSPITAL - RHCF', newName)
      newName = re.sub('SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF CENTERL QUEENS', 'SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF CENTRAL QUEENS', newName)
      newName = re.sub('SCHULMAN AND SCHACHNE INST FOR NURSING AND REHABILITATION', 'SCHULMAN AND SCHACHNE INSTITUTE FOR NURSING AND REHABILITATION', newName)
      newName = re.sub('SOLDIERS AND SAILORS MEMORIAL HOSPITAL E C U', 'SOLDIERS AND SAILORS MEMORIAL HOSPITAL EXTENDED CARE', newName)
      newName = re.sub('SPLIT ROCK REHABILITION AND HEALTH CARE CENTER', 'SPLIT ROCK REHABILITATION AND HEALTH CARE CENTER', newName)
      newName = re.sub('ST CATHERINE OF SIENA NURSING AND REHABILITATION CARE CENTER', 'ST CATHERINE OF SIENA NURSING AND REHABILITATION CARE', newName)
      newName = re.sub('ST JAMES REHABILITATION AND HEALTHCARE CENTER', 'ST. JAMES REHABILITATION AND HEALTHCARE CENTER', newName)
      newName = re.sub('ST JOSEPHS PLACE', 'ST. JOSEPHS PLACE', newName)
      newName = re.sub('ST PETERS NURSING AND REHABILITATION CENTER', 'ST. PETER\'S NURSING AND REHABILITATION CENTER', newName)
      newName = re.sub('TEN BROECK COMMONS', 'TEN BROECK CENTER FOR REHABILITATION AND NURSING', newName)
      newName = re.sub('THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING COMM', 'THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING COMMUNITY', newName)
      newName = re.sub('THE GRAND PAVILION FOR RHB AND NURSING AT ROCKVILLE CENTER', 'THE GRAND PAVILION FOR REHABILITATION AND NURSING AT ROCKVILLE', newName)
      newName = re.sub('THE GRAND REHABILITATION AND NURSING AT SOUTH POIN', 'THE GRAND REHABILITATION AND NURSING AT SOUTH POINT', newName)
      newName = re.sub('THE PAVILION AT QUEENS FOR REHABILITATION ANDNURSING', 'THE PAVILION AT QUEENS FOR REHABILITATION AND NURSING', newName)
      newName = re.sub('WATERS EDGE AT PORT JEFFERSON FOR REHABILITATION AND NURSING', 'WATERS EDGE REHABILITATION AND NURSING CENTER AT PORT JEFFERSON', newName)
      newName = re.sub('WILLIAMSBRIDGE MANOR FOR REHABILITATION AND NURSING', 'WILLIAMSBRIDGE CENTER FOR REHABILITATION AND NURSING', newName)
      newName = re.sub('WOODCREST REHABILITATION AND RESIDENTIAL H C CENTER', 'WOODCREST REHABILITATION AND RESIDENTIAL HEALTH CARE', newName)
      newName = re.sub('WORKMENS CIRCLE MULTICARE CENTER', 'WORKMEN\'S CIRCLE MULTICARE CENTER', newName)
      newName = re.sub('GURWIN JEWISH FAY J. LINDNER RESIDENCE', 'GURWIN JEWISH NURSING AND REHABILITATION CENTER', newName)

      
      return newName