# -*- coding: utf-8 -*-
import re

def normalize_cms_TX(newName):
      # print('state to be normalized: ', state)
      print('passed in facility name: ', newName)
      # TX
      
      newName = re.sub('ADVANCED REHABILITATION AND HEALTHCARE OF WICHITA', 'ADVANCED REHABILITATION AND HEALTHCARE OF WICHITA FALLS', newName)
      newName = re.sub('ARBORETUM NURSING AND REHABILITATION CENTER OF WIN', 'ARBORETUM NURSING AND REHABILITATION CENTER OF WINNIE', newName)
      newName = re.sub('BASTROP LOST PINES NURSING AND REHABILITATION CENT', 'BASTROP LOST PINES NURSING AND REHABILITATION CENTER', newName)
      newName = re.sub('BAYLOR SCOTT AND WHITE CONTINUING CARE HOSPITAL SKIL', 'BAYLOR SCOTT AND WHITE CONTINUING CARE HOSPITAL', newName)
      newName = re.sub('BRENTWOOD TERRACE HEALTHCARE AND REHABILITATION', 'BRENTWOOD TERRACE HEALTHCARE AND REHABILITATION CENTER', newName)
      newName = re.sub('BUENA VIDA NURSING AND REHAB-SAN ANTONIO', 'BUENA VIDA NURSING AND REHABILITATION SAN ANTONIO', newName)
      newName = re.sub('DELEON NURSING AND REHABILITATION', 'DE LEON NURSING AND REHABILITATION', newName)
      newName = re.sub('DEERINGS NURSING AND REHABILITATION LP', 'DEERINGS NURSING AND REHABILITATION', newName)
      newName = re.sub('EAGLE LAKE NURSING AND REHABILITATION', 'EAGLE LAKE NURSING AND REHABILITATION LP', newName)
      newName = re.sub('FREDERICKSBURG NURSING AND REHABILITATION LP', 'FREDERICKSBURG NURSING AND REHABILITATION', newName)
      newName = re.sub('FT WORTH SOUTHWEST NURSING CENTER', 'FT. WORTH WELLNESS AND REHABILITATION', newName)
      newName = re.sub('GAINESVILLE CONVALESCENT CENTER', 'GAINESVILLE NURSING AND REHABILITATION', newName)
      newName = re.sub('GARDEN TERRACE ALZHEIMER\'S CENTER OF EXCELLENCE', 'GARDEN TERRACE ALZHEIMERS CENTER OF EXCELLENCE', newName)
      newName = re.sub('GARDEN VILLA NURSING HOME AND REHABILITATION', 'GARDEN VILLA NURSING AND REHABILITATION', newName)
      
      return newName