# -*- coding: utf-8 -*-
import csv
import re

date = '2020-11-08'
# states = ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
# states = ['OH']
state = 'OH'

csv_input = date + '/states/' + state + '-' + date + '-facility-list-data-normalized'
csv_rows = []
csv_headers = []
csv_output = csv_input + '-cleaned'
headers_facility_list = ['Facility Name', 'Facility Name Normalized', 'Date Collected', 'State', 'County', 'City', 'State Facility Type', 'CTP Facility Categorization', 'State/Fed Regulated', 'State Facility ID', 'CMS Facility ID', 'Date outbreak opened', 'Date outreak closed', 'Outbreak Status', 'Resident Census', 'Resident Positives', 'Resident Probable Positives', 'Resident Deaths', 'Resident Probable Deaths', 'Staff Positive', 'Staff Probable Positives', 'Staff Deaths', 'Staff Probable Deaths', 'Resident/Staff Positives', 'Resident/Staff Probable Positives', 'Resident/Staff Deaths', 'Resident/Staff Probable Deaths', 'Resident Positives', 'Resident Probable Positives', 'Resident Deaths', 'Resident Probable Deaths', 'Staff Positive', 'Staff Probable Positives', 'Staff Deaths', 'Staff Probable Deaths', 'Resident/Staff Positives', 'Resident/Staff Probable Positives', 'Resident/Staff Deaths', 'Resident/Staff Probable Deaths', 'Residents Tested', 'Staff Tested', 'Personal Protective Equipment']

def clean_cms_data(csv_input):
    csv_input_file = csv_input + '.csv'
    with open(csv_input_file) as fin:
      csvin = csv.DictReader(fin)
      csv_headers.append(headers_facility_list)

      for row in csvin:
            providerName = row['Facility Name Normalized']
            print(row['Facility Name Normalized'])
            providerNameStrip = providerName.strip()
            newName = providerNameStrip
            # NY -> .replace(' N Y C', 'NYC').replace('N Y S ', 'NYS ').replace('N Y ', 'NY ').replace('H C F', 'HCF').replace('H R F', 'HRF').replace('R H C F', 'RHCF')
            newName = newName.replace('\n', ' ').replace('\r', ' ').replace(' HLTH ', ' HEALTH ').replace('MANOR CARE HEALTH SERVICES', 'MANORCARE HEALTH SERVICES').replace(' & ', ' AND ').replace('CTR', 'CENTER').replace('CNTR', 'CENTER').replace('REHAB ', 'REHABILITATION ').replace(', LLC', '').replace(' LLC', '').replace('  ', ' ').replace(', INC.', '').replace(', INC', '').replace(' , INC.', '').replace('HOSP ', 'HOSPITAL ')
            print(newName)
            newName = re.sub('&', ' AND ', newName)
            newName = re.sub('REHAB$', 'REHABILITATION', newName)
            newName = re.sub(', THE$', '', newName)
            newName = re.sub(', LP$', '', newName)
            newName = re.sub(', LP.$', '', newName)
            newName = re.sub(' INC$', '', newName)
            newName = re.sub(' INC.$', '', newName)
            newName = re.sub(',INC.$', '', newName)
            newName = re.sub(', LTD$', '', newName)
            newName = re.sub(' CENTE$', ' CENTER', newName)

            newNameStrip = newName.strip()
            newNameAlt = newNameStrip.strip()
            newNameAlt = re.sub(' \(THE\)$', '', newNameAlt)
            newNameAlt = re.sub(' THE$', '', newNameAlt)
            newNameAlt = re.sub(' CONV. ', ' CONVALESCENT ', newNameAlt)
            newNameAlt = re.sub(' NRSG ', ' NURSING ', newNameAlt)
            newNameAlt = re.sub(' NSG ', ' NURSING ', newNameAlt)
            newNameAlt = re.sub(' REHAB. ', ' REHABILITATION ', newNameAlt)
            newNameAlt = re.sub(' FACI$', ' FACILITY', newNameAlt)
            newNameAlt = re.sub(',$', '', newNameAlt)
            newNameAlt = re.sub('~', '', newNameAlt)
            newNameAlt = re.sub(' §$', '', newNameAlt)

            # AR

            """newNameAlt = re.sub(' OF UNION CO$', ' OF UNION COUNTY', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN SOCIETY-HOT SPRINGS VILLAGE', 'GOOD SAMARITAN SOCIETY - HOT SPRINGS VILLAGE', newNameAlt)
            # newNameALt = re.sub('HIGHLAND COURT A REHABILITATION AND RESIDENT CARE FACILITY', 'XXXHIGHLAND COURT, A REHABILITATION AND RESIDENT CARE', newNameAlt)
            newNameAlt = re.sub('MONTGOMERY CO NURSING HOME', 'MONTGOMERY COUNTY NURSING HOME', newNameAlt)
            newNameAlt = re.sub('RANDOLPH CO NURSING HOME', 'RANDOLPH COUNTY NURSING HOME', newNameAlt)
            newNameAlt = re.sub('WALNUT RIDGE N AND R', 'WALNUT RIDGE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ARKANSAS NURSING AND REHABILITATION', 'ARKANSAS NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('B RIARWOOD NURSING AND REHABILITATION CENTER', 'BRIARWOOD NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CONWAY HEALTHCARE AND REHABILITATION', 'CONWAY HEALTHCARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('G ENERAL BAPTIST NURSING HOME OF PIGGOTT', 'GENERAL BAPTIST NURSING HOME OF PIGGOTT', newNameAlt)
            newNameAlt = re.sub('GREENHOUSE COTTAGES OF POPLAR GROVE', 'THE GREEN HOUSE COTTAGES OF POPLAR GROVE', newNameAlt)
            newNameAlt = re.sub('HEATHER MANOR REHABILITATION', 'HEATHER MANOR NURSING AND REHABILITATION CENTER', newNameAlt)

            newNameAlt = re.sub('MIDTOWN POST ACUTE AND REHABILITATION-A WATERS COMMUNITY', 'MIDTOWN POST ACUTE AND REHABILITATION - A WATERS COMMUNITY', newNameAlt)
            newNameAlt = re.sub('N URSING AND REHABILITATION CENTER AT GOOD SHEPHERD', 'NURSING AND REHABILITATION CENTER AT GOOD SHEPHERD', newNameAlt)
            newNameAlt = re.sub('O AK RIDGE HEALTH AND REHABILITATION', 'OAK RIDGE HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('SOMERSET SENIOR LIVING AT MOUNT VISTA/MOUNT VISTA R AND H CENTER', 'SOMERSET SENIOR LIVING AT MOUNT VISTA', newNameAlt)
            newNameAlt = re.sub('THE GREENHOUSE COTTAGES OF BELLE MEADE', 'THE GREEN HOUSE COTTAGES OF BELLE MEADE', newNameAlt)"""


            # CA
            # newNameAlt = re.findall('\d|$', 'CRESTWOOD MANOR')[0]
            """newNameAlt = re.sub('ADVENTIST HEALTH SONORA - D/P SNF \(UNIT 6\)', 'ADVENTIST HEALTH SONORA - D/P SNF', newNameAlt)
            newNameAlt = re.sub('ADVENTIST HEALTH SONORA - D/P SNF \(UNIT 7\)', 'ADVENTIST HEALTH SONORA - D/P SNF', newNameAlt)
            newNameAlt = re.sub('CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - PEDIATRIC HOSPI', 'CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - PEDIATRIC HOSPITAL', newNameAlt)
            newNameAlt = re.sub('CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - SARATOGA PEDIAT', 'CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - SARATOGA PEDIATRIC HOSPITAL', newNameAlt)
            newNameAlt = re.sub('EASTERN PLUMAS HOSPITAL-PORTOLA CAMPUS D/P SNF', 'EASTERN PLUMAS HOSPITAL - PORTOLA CAMPUS D/P SNF', newNameAlt)
            newNameAlt = re.sub('MANCHESTER MANOR CVLT HOSPITAL', 'MANCHESTER MANOR CONVALESCENT HOSPITAL', newNameAlt)
            newNameAlt = re.sub('MARIAN REGIONAL MEDICAL CENTER DP/SNF', 'MARIAN MEDICAL CENTER D/P SNF', newNameAlt)
            newNameAlt = re.sub('MIRADA HILLS REHABILITATION AND CONVALESCENT HOSP', 'MIRADA HILLS REHABILITATION AND CONVALESCENT HOSPITAL', newNameAlt)
            newNameAlt = re.sub('PALM VILLAGE RETIREMENT COMMUNITY HEALTH CARE CENTER.', 'PALM VILLAGE RETIREMENT COMMUNITY HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SKYLINE HEALTHCARE CENTER-LOS ANGELES', 'SKYLINE HEALTHCARE CENTER - LOS ANGELES', newNameAlt)"""

            # CO
            """newNameAlt = re.sub('REHABILITATION CENTER AT SANDALWOOD,THE', 'REHABILITATION CENTER AT SANDALWOOD', newNameAlt)
            newNameAlt = re.sub ('THE SUITES PARKER', 'SUITES PARKER', newNameAlt)
            newNameAlt = re.sub ('SUITES PARKER, THE ', 'SUITES PARKER', newNameAlt)
            newNameAlt = re.sub('CENTER AT CENTERPLACE, THE ', 'CENTER AT CENTERPLACE', newNameAlt)
            # newNameAlt = re.sub('GRACE POINTE CONT CARE SR CAMPUS, SKILLED NURSING ', 'GRACE POINTE CONTINUING CARE SENIOR CAMPUS, SKILLED NURSING ', newNameAlt)
            newNameAlt = re.sub('GRACE POINTE CONT CARE SR CAMPUS, SKILLED NURSING ', 'GRACE POINTE CONTINUING CARE SENIOR CAMPUS, SKILLED NURSING', newNameAlt)"""
            
            # CT
            """newNameAlt = re.sub('THREE RIVERS HEALTHCARE*', 'THREE RIVERS HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('HARBOR VILLAGE', 'HARBOR VILLAGE NORTH HEALTH AND REHABILITATION CENTER', newNameAlt)"""

            # DC
            # newNameAlt = re.sub('', '', newNameAlt)
            """newNameAltSplit = newNameAlt.split('(')
            # this is to strip the '(bedroom values)' appended to each facility list name string
            print('1: ', newNameAltSplit[0])
            print('2: ', newNameAltSplit[1])

            newNameAlt = newNameAltSplit[0]"""


            # FL
            """newNameAlt = re.sub('WILLOWBROOKE COURT SKILLED CARE CENTER- EDGEWATER AT BOCA POINTE', 'WILLOWBROOKE COURT SKILLED CARE CENTER - EDGEWATER AT BOCA POINTE', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTH CARE CENTER-FT MYERS', 'HEARTLAND HEALTH CARE CENTER - FT MYERS', newNameAlt)
            newNameAlt = re.sub('REHABILITATION CENTER OF THE PALM BEACHES,THE', 'REHABILITATION CENTER OF THE PALM BEACHES', newNameAlt)
            newNameAlt = re.sub('BISHOP\'S GLEN RETIREMENT CENTER', 'BISHOPS GLEN RETIREMENT CENTER', newNameAlt)"""
            
            # GA
            # GRACEWOOD NSG FACILITY(UNIT 9)
            # newNameAlt = re.sub('WASHINGTON CO EXTENDED CARE FA', 'WASHINGTON CO EXTENDED CARE FACILITY', newNameAlt)
            
            # IA
            """newNameAlt = re.sub('DENVER SUNSE HOME', 'DENVER SUNSET HOME', newNameAlt)
            newNameAlt = re.sub('DUNLAP SPECIALITY CARE', 'DUNLAP SPECIALTY CARE', newNameAlt)
            newNameAlt = re.sub('PANORA SPECIALITY CARE', 'PANORA SPECIALTY CARE', newNameAlt)
            newNameAlt = re.sub('PRARIE VIEW HOME', 'PRAIRIE VIEW HOME', newNameAlt)
            newNameAlt = re.sub('PREMIER ESTATES FO MUSCATINE', 'PREMIER ESTATES OF MUSCATINE', newNameAlt)
            newNameAlt = re.sub('PREMIER ESTATES SENIOR LIFE CENTER', 'PREMIER ESTATES OF MUSCATINE', newNameAlt)
            newNameAlt = re.sub('RAVENWOOD SPECIALTY', 'RAVENWOOD SPECIALTY CARE', newNameAlt)"""

            # ID
            """newNameAlt = re.sub('ADVANCED HEALTH CARE OF COEUR D’ALENE', 'ADVANCED HEALTH CARE OF COEUR D\'ALENE', newNameAlt)
            newNameAlt = re.sub('BEAR LAKE MANOR', 'BEAR LAKE MEMORIAL SKILLED NURSING FACILITY', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN – IDAHO FALLS VILLAGE', 'GOOD SAMARITAN SOCIETY - IDAHO FALLS VILLAGE', newNameAlt)
            newNameAlt = re.sub('LIFE CARE CENTER OF COEUR D’ALENE', 'LIFE CARE CENTER OF COEUR D\'ALENE', newNameAlt)
            newNameAlt = re.sub('RIVER’S EDGE REHABILITATION', 'RIVER\'S EDGE REHABILITATION', newNameAlt)
            
            newNameAlt = re.sub('STATE VETERANS HOME - BOISE', 'IDAHO STATE VETERANS HOME - BOISE', newNameAlt)
            newNameAlt = re.sub('STATE VETERANS HOME - LEWISTON', 'IDAHO STATE VETERANS HOME - LEWISTON', newNameAlt)
            newNameAlt = re.sub('STATE VETERANS HOME – POCATELLO', 'IDAHO STATE VETERANS HOME - POCATELLO', newNameAlt)"""
                 

            # IL
            # TAYLORVILLE SKILLED NURSING (FKA MEADOW MANOR)
            """newNameAlt = re.sub('ALDEN POPLARCREEK', 'ALDEN POPLAR CREEK', newNameAlt)
            newNameAlt = re.sub('ALDEN TOWN MANOR REHABILITATION AND HEALTH CARE CENT', 'ALDEN TOWN MANOR REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('APERION CARE- PRINCETON', 'APERION CARE PRINCETON', newNameAlt)
            newNameAlt = re.sub('APERION CARE-BLOOMINGTON', 'APERION CARE BLOOMINGTON', newNameAlt)
            newNameAlt = re.sub('AVANTARA OF ELGIN','AVANTARA ELGIN', newNameAlt)
            newNameAlt = re.sub('BRIA FOREST EDGE', 'BRIA OF FOREST EDGE', newNameAlt)
            newNameAlt = re.sub('BRIA RIVER OAKS', 'BRIA OF RIVER OAKS', newNameAlt)
            newNameAlt = re.sub('BURBANK REHABILITATION - VERA CARE STICKNEY', 'BURBANK REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CALIFORNIA GARDENS NURSING AND REHABILITATION CENT', 'CALIFORNIA GARDENS NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CHAMPAIGN-URBANA NURSING AND REHABILITATION', 'CHAMPAIGN URBANA NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('CITADEL CARE CENTER OF KANKAKEE', 'CITADEL OF KANKAKEE', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH EL PASO', 'HERITAGE HEALTH - EL PASO', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH JACKSONVILLE', 'HERITAGE HEALTH - JACKSONVILLE', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH MENDOTA', 'HERITAGE HEALTH - MENDOTA', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH OF NORMAL', 'HERITAGE HEALTH - NORMAL', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH OF PANA', 'HERITAGE HEALTH - PANA', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH PERU', 'HERITAGE HEALTH - PERU', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH SPRINGFIELD', 'HERITAGE HEALTH - SPRINGFIELD', newNameAlt)
            newNameAlt = re.sub('HERITAGE HEALTH: THERAPY AND SENIOR CARE - SPRINGFIE', 'HERITAGE HEALTH: THERAPY AND SENIOR CARE - SPRINGFIELD', newNameAlt)
            newNameAlt = re.sub('LAKE COOK REHABILITATION AND HEALTHCARE(FORMERLY ROSEWOOD)', 'LAKE COOK REHABILITATION AND HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('LITTLE SISTERS OF THE POOR ST MARYS HOME', 'LITTLE SISTERS OF THE POOR/ST. MARYS HOME', newNameAlt)
            newNameAlt = re.sub('PRARIEVIEW AT THE GARLANDS', 'PRAIRIEVIEW AT THE GARLANDS', newNameAlt)
            newNameAlt = re.sub('TAYLORVILLE SKILLED NURSING \(FKA MEADOW MANOR\)', 'TAYLORVILLE SKILLED NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('PACTT LEARNING -OAK PARK', 'PACTT LEARNING - OAK PARK', newNameAlt)
            newNameAlt = re.sub('PA PETERSON AT THECITADEL', 'PA PETERSON AT THE CITADEL', newNameAlt)
            newNameAlt = re.sub('UNIVERSITY REHABILITATION AT NORTHMOOR', 'UNIVERSITY REHABILITATION CENTER AT NORTHMOOR', newNameAlt)"""

            # KY 
            """newNameAlt = re.sub('LEE COUNTY CARE AND REHABILITATION', 'LEE COUNTY CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SPRINGFIELD NURSING AND REHABILITATION', 'SPRINGFIELD NURSING AND REHABILITATION CENTER', newNameAlt)"""

            #KS
            # this is to strip the '( - MONTH YEAR)' appended to each facility list name string
            """newNameAltSplit = newNameAlt.split('-')
            print('1: ', newNameAltSplit[0])
            # print('2: ', newNameAltSplit[1])
            newNameAlt = newNameAltSplit[0]
            newNameAlt = re.sub('PLAZE WEST HEALTHCARE AND REHABILITATION CENTER', 'PLAZA WEST HEALTHCARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('ROSSVILLE HEALTHCARE AND REHAV', 'ROSSVILLE HEALTHCARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('TOPEKA PREBYTERIAN MANOR', 'TOPEKA PRESBYTERIAN MANOR', newNameAlt)"""



            # LA
            # LANDMARK OF PLAQUEMINE*
            """newNameAlt = re.sub('HARMONY HOUSE NURSING AND REHABILITATION CENTER.', 'HARMONY HOUSE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LANDMARK OF PLAQUEMINE*', 'LANDMARK OF PLAQUEMINE', newNameAlt)
            newNameAlt = re.sub('SOUTHERN OAKS NURSING AND REHABILITATION CENTER.', 'SOUTHERN OAKS NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('TERREBONNE GEN. MED. CENTER - SNF', 'TERREBONNE GENERAL MEDICAL CENTER - SNF', newNameAlt)"""
            
            # MA

            # MD  


            # ME 
            # newNameAlt = re.sub('MAINE VETERANS HOME', 'MAINE VETERANS HOME - SCARBOROUGH', newNameAlt)

            # MI
            # THE OASIS AT MONROE REHABILITATION AND NUR
            # OCEANA CO MD CARE FACILITY
            # IRON CO MEDICAL CARE FACILITY
            # HILLSDALE CO MEDICAL CARE FACILITY
            # HALLMARK LIVING--BENTON HARBOR
            """newNameAlt = re.sub('ADVANTAGE LIVING CENTER HARPER WOODS', 'ADVANTAGE LIVING CENTER - HARPER WOODS', newNameAlt)
            newNameAlt = re.sub('ADVANTAGE LIVING CENTER NORTHWEST', 'ADVANTAGE LIVING CENTER - NORTHWEST', newNameAlt)
            newNameAlt = re.sub('ADVANTAGE LIVING CENTER REDFORD', 'ADVANTAGE LIVING CENTER - REDFORD', newNameAlt)
            newNameAlt = re.sub('ADVANTAGE LIVING CENTER SOUTHGATE', 'ADVANTAGE LIVING CENTER - SOUTHGATE', newNameAlt)
            newNameAlt = re.sub('ADVANTAGE LIVING CENTER WAYNE', 'ADVANTAGE LIVING CENTER - WAYNE', newNameAlt)
            newNameAlt = re.sub('AERIUS HEALTH CENTER ', 'AERIUS HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('BEAUMONT REHABILITATION AND CONTINUING CARE - DBN', 'BEAUMONT REHABILITATION AND CONTINUING CARE - DEARBORN', newNameAlt)
            newNameAlt = re.sub('BEAUMONT REHABILITATION AND CONTINUING CARE FARMING', 'BEAUMONT REHABILITATION AND CONTINUING CARE - FARMINGTON HILLS', newNameAlt)
            newNameAlt = re.sub('CAMBRIDGE NORTH HEALTHCARE CENTER ', 'CAMBRIDGE NORTH HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('CHIPPEWA COUNTY WAR MEM HOSPITAL LTCU', 'CHIPPEWA COUNTY WAR MEMORIAL HOSPITAL LTCU', newNameAlt)
            newNameAlt = re.sub('GOGEBIC MEDICAL CARE FACILITY ', 'GOGEBIC MEDICAL CARE FACILITY', newNameAlt)
            newNameAlt = re.sub('HALLMARK LIVING--BENTON HARBOR', 'HALLMARK LIVING BENTON HARBOR', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC - ANN ARBOR', 'HEARTLAND HEALTH CARE CENTER - ANN ARBOR', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC - BATTLE CREEK', 'HEARTLAND HEALTH CARE CENTER - BATTLE CREEK', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC - GROSSE POINTE WOODS', 'HEARTLAND HEALTH CARE CENTER - GROSSE POINT WOODS', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC - HAMPTON', 'HEARTLAND HEALTH CARE CENTER - HAMPTON', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC BRIARWOOD', 'HEARTLAND HEALTH CARE CENTER - BRIARWOOD', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HCC FOSTRIAN', 'HEARTLAND HEALTH CARE CENTER - FOSTRIAN', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTH CARE CENTER - THREE RIV', 'HEARTLAND HEALTH CARE CENTER - THREE RIVERS', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTH CARE CENTER ALLEN PARK', 'HEARTLAND HEALTH CARE CENTER - ALLEN PARK', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTH CARE CENTER-LIVONIA', 'HEARTLAND HEALTH CARE CENTER - LIVONIA', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTHCARE - STERLING HEIGHTS', 'HEARTLAND HEALTH CARE CENTER - STERLING HEIGHTS', newNameAlt)
            newNameAlt = re.sub('HENRY FORD VILLAGE $', 'HENRY FORD VILLAGE', newNameAlt)
            newNameAlt = re.sub('JACKSON COUNTY MEDICAL CARE FACILITY ', 'JACKSON COUNTY MEDICAL CARE FACILITY', newNameAlt)
            newNameAlt = re.sub('LENAWEE MEDICAL CARE FACILITY ', 'LENAWEE MEDICAL CARE FACILITY', newNameAlt)
            newNameAlt = re.sub('LIFE CARE CENTER OF PLAINWELL ', 'LIFE CARE CENTER OF PLAINWELL', newNameAlt)
            newNameAlt = re.sub('LOURDES REHABILITATION AND HEALTHCARE ', 'LOURDES REHABILITATION AND HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('MARVIN AND BETTY DANTO FAMILY HEALTH CARE ', 'MARVIN AND BETTY DANTO FAMILY HEALTH CARE', newNameAlt)
            newNameAlt = re.sub('MEADOW BROOK MCF', 'MEADOW BROOK MEDICAL CARE FACILITY', newNameAlt)
            newNameAlt = re.sub('MEDILODGE ALPENA', 'MEDILODGE OF ALPENA', newNameAlt)
            newNameAlt = re.sub('MEDILODGE OF CHEBOYGAN ', 'MEDILODGE OF CHEBOYGAN', newNameAlt)
            newNameAlt = re.sub('MEDILODGE OF PLYMOUTH ', 'MEDILODGE OF PLYMOUTH', newNameAlt)
            newNameAlt = re.sub('MEDILODGE OF PORT HURON ', 'MEDILODGE OF PORT HURON', newNameAlt)
            newNameAlt = re.sub('MUNSON HEALTH CRAWFORD CONTINUING CARE ', 'MUNSON HEALTH CRAWFORD CONTINUING CARE', newNameAlt)
            newNameAlt = re.sub('PLAINWELL PINES NURSING AND REHAB.', 'PLAINWELL PINES NURSING AND REHAB', newNameAlt)
            newNameAlt = re.sub('REGENCY A VILLA CENTER ', 'REGENCY A VILLA CENTER', newNameAlt)
            newNameAlt = re.sub('SAMARITAS  SENIOR LIVING SAGINAW', 'SAMARITAS SENIOR LIVING SAGINAW', newNameAlt)
            newNameAlt = re.sub('SKLD LIVONIA ', 'SKLD - LIVONIA', newNameAlt)
            newNameAlt = re.sub('SKLD BELTLINE', 'SKLD - BELTLINE', newNameAlt)
            newNameAlt = re.sub('SKLD IONIA', 'SKLD - IONIA', newNameAlt)
            newNameAlt = re.sub('SKLD LEONARD', 'SKLD - LEONARD', newNameAlt)
            newNameAlt = re.sub('SKLD MUSKEGON', 'SKLD - MUSKEGON', newNameAlt)
            newNameAlt = re.sub('SKLD PLYMOUTH', 'SKLD - PLYMOUTH', newNameAlt)
            newNameAlt = re.sub('SKLD WHITEHALL', 'SKLD - WHITEHALL', newNameAlt)
            newNameAlt = re.sub('SKLD WYOMING', 'SKLD - WYOMING', newNameAlt)
            newNameAlt = re.sub('SKLD ZEELAND', 'SKLD - ZEELAND', newNameAlt)
            newNameAlt = re.sub('SPECENTERUM HEALTH REHABILITATION AND NURSING FULLER', 'SPECENTERUM HEALTH REHABILITATION AND NURSING - FULLER', newNameAlt)
            newNameAlt = re.sub('SPECENTERUM HEALTH RNC - KELSEY HOSPITAL', 'SPECENTERUM HEALTH REHABILITATION AND NURSING CENTER - KELSEY HOSPITAL', newNameAlt)
            newNameAlt = re.sub('SPECENTERUM HEALTH RNC - UNITED HOSPITAL', 'SPECENTERUM HEALTH REHABILITATION AND NURSING CENTER - UNITED HOSPITAL', newNameAlt)
            newNameAlt = re.sub('STRATFORD PINES ', 'STRATFORD PINES', newNameAlt)
            newNameAlt = re.sub('THE OASIS AT MONROE REHABILITATION AND NUR', 'THE OASIS AT MONROE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('THE RIVERS HEALTH AND REHABILITATION CENTER OF GROSSE PT', 'THE RIVERS HEALTH AND REHABILITATION CENTER OF GROSSE POINTE', newNameAlt)
            newNameAlt = re.sub('THE WILLOWS AT HOWELL ', 'THE WILLOWS AT HOWELL', newNameAlt)
            newNameAlt = re.sub('TUSCOLA COUNT MEDICAL CARE COMMUNITY ', 'TUSCOLA COUNTY MEDICAL CARE FACILITY', newNameAlt)
            newNameAlt = re.sub('VILLA AT ROSE CITY ', 'THE VILLA AT ROSE CITY', newNameAlt)
            newNameAlt = re.sub('VILLA AT SILVERBELL ESTATE', 'THE VILLA AT SILVERBELL ESTATES', newNameAlt)
            newNameAlt = re.sub('VILLA AT WEST BRANCH', 'THE VILLA AT WEST BRANCH', newNameAlt)
            # newNameAlt = re.sub('WELLBRIDGE OF GRAND BLANC ', 'WELLBRIDGE OF GRAND BLANC', newNameAlt)
            newNameAlt = re.sub('WELLBRIDGE OF PINCKNEY ', 'WELLBRIDGE OF PINCKNEY', newNameAlt)
            newNameAlt = re.sub('WOODHAVEN RETIREMENT COMMUNITY ', 'WOODHAVEN RETIREMENT COMMUNITY', newNameAlt)"""

            
            #NC 
            """newNameAlt = re.sub('ACCORDIUS HEALTH$', 'ACCORDIUS HEALTH AT GREENSBORO', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS HEALTH - GASTONIA', 'ACCORDIUS HEALTH AT GASTONIA', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS HEALTH OF CLEMMONS', 'ACCORDIUS HEALTH AT CLEMMONS', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS HEALTH OF SALISBURY', 'ACCORDIUS HEALTH AT SALISBURY', newNameAlt)
            newNameAlt = re.sub('ASBURY HEALTH AND REHABILITATION', 'ASBURY HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CAROLINA REHABILITATION CENTER', 'CAROLINA REHABILITATION CENTER OF CUMBERLAND', newNameAlt)
            newNameAlt = re.sub('CAROLINA REHABILITATION OF BURKE', 'CAROLINA REHABILITATION CENTER OF BURKE', newNameAlt)
            newNameAlt = re.sub('FAIR HAVEN HOME- BOSTIC', 'FAIR HAVEN HOME', newNameAlt)
            newNameAlt = re.sub('KENANSVILLE HEALTH AND REHABILITATION', 'KENANSVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LIBERTY COMMONS NURSING AND REHABILITATION$', 'LIBERTY COMMONS NURSING AND REHABILITATION CENTER OF ROWAN COUNTY', newNameAlt)
            newNameAlt = re.sub('LIBERTY COMMONS NURSING AND REHABILITATION CENTER OF JOHNSTON CTY', 'LIBERTY COMMONS NURSING AND REHABILITATION CENTER OF JOHNSTON COUNTY', newNameAlt)
            newNameAlt = re.sub('NC STATE VETERANS HOME$', 'NC STATE VETERANS HOME-KINSTON', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES ALAMANCE', 'PEAK RESOURCES - ALAMANCE', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES CHERRYVILLE', 'PEAK RESOURCES - CHERRYVILLE', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES LTCF', 'PEAK RESOURCES - OUTER BANKS', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES PINE LAKE CARTHAGE', 'PEAK RESOURCES - PINELAKE', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES SHELBY', 'PEAK RESOURCES - SHELBY', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES-OUTER BANKS', 'PEAK RESOURCES - OUTER BANKS', newNameAlt)
            newNameAlt = re.sub('PELICAN HEALTH', 'PELICAN HEALTH THOMASVILLE', newNameAlt)
            newNameAlt = re.sub('PRUITT HEALTH DURHAM', 'PRUITT HEALTH - DURHAM', newNameAlt)
            newNameAlt = re.sub('PRUITTHEALTH FARMVILLE', 'PRUITT HEALTH - FARMVILLE', newNameAlt)
            newNameAlt = re.sub('PRUITTHEALTH-ROCKINGHAM', 'PRUITT HEALTH - ROCKINGHAM', newNameAlt)
            newNameAlt = re.sub('SIGNATURE HEALTHCARE$', 'SIGNATURE HEALTHCARE OF CHAPEL HILL', newNameAlt)
            newNameAlt = re.sub('SIGNATURE HEALTHCARE KINSTON', 'SIGNATURE HEALTHCARE OF KINSTON', newNameAlt)
            newNameAlt = re.sub('UNIVERSAL HEALTH CARE/GREENVILLE', 'UNIVERSAL HEALTH CARE / GREENVILLE', newNameAlt)
            newNameAlt = re.sub('UNIVERSAL HEALTH CARE/OXFORD', 'UNIVERSAL HEALTH CARE / OXFORD', newNameAlt)
            newNameAlt = re.sub('UNIVERSAL HEALTHCARE$', 'UNIVERSAL HEALTH CARE / LILLINGTON', newNameAlt)
            newNameAlt = re.sub('UNIVERSAL HEALTHCARE RAMSEUR', 'UNIVERSAL HEALTH CARE / RAMSEUR', newNameAlt)
            newNameAlt = re.sub('VA COMMUNITY LIVING CENTER, FAYETTEVILLE', 'NC STATE VETERANS HOME - FAYETTEVILLE', newNameAlt)
            newNameAlt = re.sub('WHISPERING PINES', 'WHISPERING PINES NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('WHITE OAK MANOR WAXHAW', 'WHITE OAK MANOR - WAXHAW', newNameAlt)
            newNameAlt = re.sub('WHITE OAK MANOR-KINGS MOUNTAIN', 'WHITE OAK MANOR - KINGS MOUNTAIN', newNameAlt)
            newNameAlt = re.sub('WHITE OAK MANOR$', 'WHITE OAK MANOR - BURLINGTON', newNameAlt)"""


            # ND
            """newNameAlt = re.sub('MAPLE VIEW MEMORY CARE- BISMARCK', 'MAPLE VIEW MEMORY CARE - BISMARCK', newNameAlt)
            newNameAlt = re.sub('MCKENZIE COUNTY-GOOD SHEPHERD LONG TERM CARE', 'MCKENZIE COUNTY - GOOD SHEPHERD LONG TERM CARE', newNameAlt)
            newNameAlt = re.sub('PEAK RESOURCES ', 'PEAK RESOURCES - ', newNameAlt)
            # newNameAlt = re.sub('EVENTIDE$', 'EVENTIDE FARGO', newNameAlt)
            # newNameAlt = re.sub('EVENTIDE DOWNTOWN','', newNameAlt)
            newNameAlt = re.sub('EVENTIDE JAMESTOWN','EVENTIDE JAMESTOWN ASSISTED LIVING', newNameAlt)
            newNameAlt = re.sub('EVENTIDE SHEYENNE CROSSINGS','EVENTIDE SHEYENNE CROSSINGS ASSISTED LIVING', newNameAlt)
            newNameAlt = re.sub('GOOD SAM, LAKOTA', 'GOOD SAMARITAN SOCIETY - LAKOTA', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN BOTTINEAU', 'GOOD SAMARITAN SOCIETY - BOTTINEAU', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN FARGO', 'GOOD SAMARITAN SOCIETY - FARGO', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN LAKOTA','GOOD SAMARITAN SOCIETY - LAKOTA', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN MOHALL', 'GOOD SAMARITAN SOCIETY - MOHALL', newNameAlt)
            # newNameAlt = re.sub('GOOD SAMARITAN MOTT', 'GOOD SAMARITAN SOCIETY - MOTT', newNameAlt)
            newNameAlt = re.sub('GOOD SAM MOTT', 'GOOD SAMARITAN SOCIETY - MOTT', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN OAKES', 'GOOD SAMARITAN SOCIETY - OAKES', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN PARK RIVER', 'GOOD SAMARITAN SOCIETY - PARK RIVER', newNameAlt)
            # newNameAlt = re.sub('HEART OF AMERICA', 'HEART OF AMERICA CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MCKENZIE COUNTY HEALTH-GOOD SHEPHERD','MCKENZIE COUNTY - GOOD SHEPHERD LONG TERM CARE', newNameAlt)"""
            

            # NJ
            # SOMERSET WOODS REHABILITATION AND NURSING CENTER §
            """newNameAlt = re.sub('ALARIS AT CASTLE HILL', 'ALARIS HEALTH AT CASTLE HILL', newNameAlt)
            newNameAlt = re.sub('ARISTCARE AT WHITING', 'ARISTACARE AT WHITING', newNameAlt)
            newNameAlt = re.sub('CAREONE AT EVESHAM AL', 'CARE ONE AT EVESHAM', newNameAlt)
            newNameAlt = re.sub('CAREONE AT VALLEY', 'CARE ONE AT VALLEY', newNameAlt)
            newNameAlt = re.sub('CAREONE AT MOORESTOWN', 'CARE ONE AT MOORESTOWN', newNameAlt)
            newNameAlt = re.sub('CHESTNUT HILL RESIDENCE', 'CHESTNUT HILL CONVALESCENT CENTER', newNameAlt)
            newNameAlt = re.sub('INGLEMOOR REHABILITATION AND CARE CENTER OF LIIVNGSTON', 'INGLEMOOR REHABILITATION AND CARE CENTER OF LIVINGSTON', newNameAlt)
            newNameAlt = re.sub('MANORCARE VOORHEES', 'MANOR CARE HEALTH SERVICES - VOORHEES', newNameAlt)
            newNameAlt = re.sub('MAPLE GLEN CENTER \(GENESIS HEALTH CARE\)', 'MAPLE GLEN CENTER', newNameAlt)
            newNameAlt = re.sub('MERIDIAN NURSING AND REHABILITATION AR BRICK', 'MERIDIAN NURSING AND REHABILITATION AT BRICK', newNameAlt)
            newNameAlt = re.sub('ANDOVER SUBACUTE AND REHABILITATION II', 'ANDOVER SUBACUTE AND REHABILITATION CENTER II', newNameAlt)"""

            # NM
            """newNameAlt = re.sub('BLOOMFIELD NURSING AND REHABILITATION CENTER, BLOOMFIELD', 'BLOOMFIELD NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CASA ARENA BLANCA NURSING CENTER, ALAMOGORDO', 'CASA ARENA BLANCA NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('CASA DE ORO CENTER, LAS CRUCES', 'CASA DE ORO CENTER', newNameAlt)
            newNameAlt = re.sub('CASA MARIA, ROSWELL', 'CASA MARIA HEALTHCARE CENTER AND PECOS VALLEY REHABILITATION', newNameAlt)
            newNameAlt = re.sub('CLOVIS HEALTHCARE AND REHABILITATION CLOVIS', 'CLOVIS HEALTHCARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('GOOD SAMARITAN, LAS CRUCES', 'GOOD SAMARITAN SOCIETY - LAS CRUCES', newNameAlt)
            newNameAlt = re.sub('MISSION ARCH CENTER (ROSWELL)', 'MISSION ARCH CENTER', newNameAlt)
            newNameAlt = re.sub('RATON NURSING AND REHABILITATION CENTER, RATON', 'RATON NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('RETIREMENT RANCHES-CLOVIS', 'RETIREMENT RANCHES', newNameAlt)
            newNameAlt = re.sub('SANDIA RIDGE GENESIS, ALBUQUERQUE', 'SANDIA RIDGE GENESIS', newNameAlt)
            newNameAlt = re.sub('SUNSET VILLA NURSING HOME, ROSWELL', 'SUNSET VILLA NURSING HOME', newNameAlt)
            newNameAlt = re.sub('VILLAGE AT NORTHRISE, LAS CRUCES', 'VILLAGE AT NORTHRISE', newNameAlt)
            newNameAlt = re.sub('WHITE SANDS HEALTHCARE, HOBBS', 'WHITE SANDS HEALTHCARE', newNameAlt)"""

            # NY


            """
            .replace(' N Y C', 'NYC')
            .replace('N Y S ', 'NYS ')
            .replace('N Y ', 'NY ')
            .replace('H C F', 'HCF')
            .replace('H R F', 'HRF')
            .replace('R H C F', 'RHCF')"""
            """newNameAlt = re.sub('BROOKLYN CENTER FOR REHABILITATION AND RESIDENTIAL', 'BROOKLYN CENTER FOR REHABILITATION AND RESIDENTIAL HEALTH CARE', newNameAlt)
            newNameAlt = re.sub('COMPREHENSIVE REHABILITATION AND NURSING CENTER AT', 'COMPREHENSIVE REHABILITATION AND NURSING CENTER AT WILLIAMSVILLE', newNameAlt)
            newNameAlt = re.sub('HAVEN MANOR HEALTH CARE CENTER,LLC', 'HAVEN MANOR HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('HUDSON POINTE AT RIVERDALE CENTER FOR NURSING AND', 'HUDSON POINTE AT RIVERDALE CENTER FOR NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('KATHERINE LUTHER RESIDENTIAL HEALTH CARE AND', 'KATHERINE LUTHER RESIDENTIAL HEALTH CARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('NORTHWELL HEALTH STERN FAMILY CENTER FOR', 'NORTHWELL HEALTH STERN FAMILY CENTER FOR REHABILITATION', newNameAlt)
            newNameAlt = re.sub('RICHMOND CENTER FOR REHABILITATION AND SPECIALTY', 'RICHMOND CENTER FOR REHABILITATION AND SPECIALTY HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF', 'SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF CENTRAL QUEENS', newNameAlt)
            newNameAlt = re.sub('SCHULMAN AND SCHACHNE INSTITUTE FOR NURSING AND', 'SCHULMAN AND SCHACHNE INSTITUTE FOR NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('SEA VIEW HOSPITAL, REHABILITATION CENTER AND HOME', 'SEA VIEW HOSPITAL REHABILITATION CENTER AND HOME', newNameAlt)
            newNameAlt = re.sub('SPLIT ROCK REHABILITION AND HEALTH CARE CENTER', 'SPLIT ROCK REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('THE BROOK AT HIGH FALLS NURSING HOME AND REHABILITATION', 'THE BROOK AT HIGH FALLS NURSING HOME AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('THE CHATEAU AT BROOKLYN REHABILITATION AND NURSING', 'THE CHATEAU AT BROOKLYN REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING', 'THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING COMMUNITY', newNameAlt)
            newNameAlt = re.sub('THE PARAMOUNT AT SOMERS REHABILITATION AND NURSING', 'THE PARAMOUNT AT SOMERS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('THE PINES AT GLENS FALLS CENTER FOR NURSING  AND', 'THE PINES AT GLENS FALLS CENTER FOR NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('THE PINES AT POUGHKEEPSIE CENTER FOR NURSING  AND', 'THE PINES AT POUGHKEEPSIE CENTER FOR NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('THE VALLEY VIEW CENTER FOR NURSING CARE AND', 'THE VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('THE WILLOWS AT RAMAPO REHABILITATION AND NURSING', 'THE WILLOWS AT RAMAPO REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('VILLAGECARE REHABILITATION AND NURSING CENTER', 'VILLAGE CARE REHABILITATION AND NURSING CENTER', newNameAlt)"""

            # OK
            newNameAlt = re.sub('QUAIL RIDGE LIVING CENTER \(COLCORD, OK\)', 'QUAIL RIDGE LIVING CENTER', newNameAlt)
            
            # OH
            newNameAlt = re.sub('ABBYSHIRE', 'ABBYSHIRE PLACE SKILLED NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ACCORD CARE COMMUNITY', 'ACCORD CARE COMMUNITY MIDDLEBURG HEIGHTS', newNameAlt)
            newNameAlt = re.sub('ADDISON HEIGHTS HEALTH AND REHABILITATION', 'ADDISON HEIGHTS HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ADVANCED HEALTH CARE', 'ADVANCED HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('ALTERCARE BUCYRUS', 'ALTERCARE OF BUCYRUS', newNameAlt)
            newNameAlt = re.sub('ALTERCARE IN CANAL WINCHESTER', 'ALTERCARE OF CANAL WINCHESTER POST-ACUTE RC', newNameAlt)
            newNameAlt = re.sub('ALTERCARE MENTOR', 'ALTERCARE OF MENTOR', newNameAlt)
            newNameAlt = re.sub('ALTERCARE OF ALLIANCE', 'ALTERCARE OF ALLIANCE CENTER FOR REHABILITATION AND NC', newNameAlt)
            newNameAlt = re.sub('ALTERCARE OF LOUISVILLE', 'ALTERCARE OF LOUISVILLE CENTER FOR REHABILITATION AND NURSING CARE', newNameAlt)
            newNameAlt = re.sub('ALTERCARE OF MAYFIELD', 'ALTERCARE OF MAYFIELD VILLAGE', newNameAlt)
            newNameAlt = re.sub('ANCHOR LODGE', 'ANCHOR LODGE NURSING HOME', newNameAlt)
            newNameAlt = re.sub('ARBORS OF GALLIPOLIS', 'ARBORS AT GALLIPOLIS', newNameAlt)
            newNameAlt = re.sub('ARBORS OF MILFORD', 'ARBORS AT MILFORD', newNameAlt)
            newNameAlt = re.sub('ARBORS OF MINERVA', 'ARBORS AT MINERVA', newNameAlt)
            newNameAlt = re.sub('ARBORS-WEST JEFFERSON', 'ARBORS AT WEST JEFFERSON', newNameAlt)
            newNameAlt = re.sub('ARISTOCRAT', 'ARISTOCRAT BEREA HEALTHCARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('ARLINGTON COURT', 'ARLINGTON COURT NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ASTORIA PLACE$', 'ASTORIA PLACE OF BARNESVILLE', newNameAlt)
            newNameAlt = re.sub('AURORA MANOR', 'AURORA MANOR SPECIAL CARE CENTER', newNameAlt)
            newNameAlt = re.sub('AUSTINTOWN HEALTHCARE', 'AUSTINTOWN HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('AUSTINWOODS', 'AUSTINWOODS REHABILITATION HEALTH CARE', newNameAlt)
            newNameAlt = re.sub('AUTUMN AEGIS', 'AUTUMN AEGIS NURSING HOME', newNameAlt)
            newNameAlt = re.sub('AVENUE OF AURORA', 'AVENUE AT AURORA', newNameAlt)
            newNameAlt = re.sub('AVON OAKS', 'AVON OAKS NURSING HOME', newNameAlt)
            newNameAlt = re.sub('BEACHWOOD POINTE', 'BEACHWOOD POINTE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BEEGHLY OAKS FOR REHABILITATION', 'BEEGHLY OAKS CENTER FOR REHABILITATION AND HEALING', newNameAlt)
            newNameAlt = re.sub('BELPRE LANDING', 'BELPRE LANDING NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('BENNINGTON GLEN', 'BENNINGTON GLEN NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('BEST CARE', 'BEST CARE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('BIRCHAVEN', 'BIRCHAVEN RETIREMENT VILLAGE', newNameAlt)
            newNameAlt = re.sub('BIRCHWOOD-HILLANDALE', 'BIRCHWOOD CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BLOSSOM NURSING AND REHABILITATION', 'BLOSSOM NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('BRENTWOOD HEALTHCARE CENTER', 'BRENTWOOD HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BRETHREN CARE VILLAGE', 'BRETHREN CARE VILLAGE HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BRIDGETOWN NURSING HOME', 'BRIDGETOWN NURSING AND REHABILITATION CENTRE', newNameAlt)
            newNameAlt = re.sub('BROADVIEW MULTICARE', 'BROADVIEW MULTI CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BROOKWOOD', 'BROOKWOOD RETIREMENT COMMUNITY', newNameAlt)
            newNameAlt = re.sub('BROWN MEMORIAL', 'BROWN MEMORIAL HOME', newNameAlt)
            newNameAlt = re.sub('BRUNSWICK POINTE', 'BRUNSWICK POINTE TRANSITIONAL CARE', newNameAlt)
            newNameAlt = re.sub('BURBANK PARKE', 'BURBANK PARKE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BURLINGTON HOUSE', 'BURLINGTON HOUSE REHABILITATION AND ALZHEIMER\'S CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BURTON HEALTHCARE', 'BURTON HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CANFIELD HEALTHCARE', 'CANFIELD HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('CAPRICE HEALTHCARE', 'CAPRICE HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CARDINAL WOODS SKILLED NURSING AND REHABILITATION', 'CARDINAL WOODS SKILLED NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CARECORE AT LIMA', 'CARE CORE AT LIMA', newNameAlt)
            newNameAlt = re.sub('CARLISLE MANOR', 'CARLISLE MANOR HEALTH CARE', newNameAlt)
            newNameAlt = re.sub('CEDAR OF LEBANON', 'CEDARS OF LEBANON CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CEDAR VILLAGE', 'CEDAR VILLAGE SENIOR LIVING', newNameAlt)
            newNameAlt = re.sub('CEDARVIEW', 'CEDARVIEW CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CLOVERNOOK', 'CLOVERNOOK HEALTH CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('COLONIAL$', 'COLONIAL NURSING CENTER OF ROCKFORD', newNameAlt)
            newNameAlt = re.sub('CONCORD CARE$', 'CONCORD CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CONCORD CARE CENTER', 'CONCORD CARE CENTER OF TOLEDO', newNameAlt)
            newNameAlt = re.sub('CONTINENTAL MANOR', 'CONTINENTAL MANOR NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CONTINUING HEALTH CARE$', 'CONTINUING HEALTHCARE OF TOLEDO', newNameAlt)
            newNameAlt = re.sub('CONTINUING HEALTHCARE AT THE RIDGE', '', newNameAlt)
            newNameAlt = re.sub('COUNTRY LANE GARDENS REHABILITATION AND NURSING', 'COUNTRY LANE GARDENS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('COUNTRY LAWN', 'COUNTRY LAWN CENTER FOR REHABILITATION', newNameAlt)
            newNameAlt = re.sub('COUNTRY MEADOWS', 'COUNTRY MEADOW REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('COVENANT VILLAGE', 'COVENANT VILLAGE OF GREEN TOWNSHIP', newNameAlt)
            newNameAlt = re.sub('CRESTVIEW', 'CRESTVIEW REHABILITATION AND SKILLED NURSING SERVICES', newNameAlt)
            newNameAlt = re.sub('CRESTWOOD RIDGE', 'CRESTWOOD RIDGE SKILLED NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('CUMBERLAND POINTE', 'CUMBERLAND POINTE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CYPRESS POINTE', 'CYPRESS POINTE HEALTH CAMPUS', newNameAlt)
            newNameAlt = re.sub('DARBY GLEN NURSING AND REHABILITATION', 'DARBY GLENN NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('DAYSPRING OF MIAMI VALLEY', 'DAYSPRING OF MIAMI VALLEY HEALTH CARE CENTER AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('DUNBAR HEALTH AND REHABILITATION', 'DUNBAR HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('EAST PARK RETIREMENT', 'EAST PARK CARE CENTER', newNameAlt)
            newNameAlt = re.sub('EASTGATESPRING REHABILITATION NURSING CARE CENTER', 'EASTGATE HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('EASTLAND HEALTHCARE AND REHABILITATION', 'EASTLAND HEALTH CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ECHO MANOR NURSING AND REHABILITATION -PICKERINGTON', 'ECHO MANOR NURSING AND REHABILITATION - PICKERINGTON', newNameAlt)
            newNameAlt = re.sub('EDGEWOOD MANOR$', 'EDGEWOOD MANOR REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('ENNIS COURT', 'ENNIS COURT NURSING CARE', newNameAlt)
            newNameAlt = re.sub('EUCLID BEACH', 'EUCLID BEACH HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('EVERGREEN MANOR', 'EVERGREEN HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('FAIRFAX HEALTHCARE', 'FAIRFAX HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('FALLING WATERS - STRONGSVILLE', 'FALLING WATER HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('FIRST COMMUNITY VILLAGE', 'FIRST COMMUNITY VILLAGE HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('FOUR SEASONS OF WASHINGTON', 'FOUR SEASONS OF WASHINGTON NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('FRANCISCAN CARE CENTER', 'FRANCISCAN CARE CENTER SYLVANIA', newNameAlt)
            newNameAlt = re.sub('FRANKLIN PLAZA', 'FRANKLIN PLAZA EXTENDED CARE', newNameAlt)
            newNameAlt = re.sub('FULTON MANOR', 'FULTON MANOR NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('GARDEN COURT', 'GARDEN COURT NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('GEM CITY NURSING AND REHABILITATION', 'GEM CITY NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('GENEVA SHORES', 'GENEVA SHORES NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('GILLETTES', 'GILLETTE NURSING HOME', newNameAlt)
            newNameAlt = re.sub('GLENDALE PLACE', 'GLENDALE PLACE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('GLENDORA HEALTHCARE CENTER', 'GLENDORA HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('GOLDEN YEARS', 'GOLDEN YEARS NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('GRAND POINTE', 'GRANDE POINTE HEALTH CARE COMMUNITY', newNameAlt)
            newNameAlt = re.sub('GREEN VILLAGE SKILLED NURSING', 'GREEN VILLAGE SKILLED NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('GREENBRIER$', 'GREENBRIER HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('HAMPTON WOODS', 'HAMPTON WOODS NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('HARBOR HEALTH CARE', 'HARBOR HEALTH CARE OF IRONTON', newNameAlt)
            newNameAlt = re.sub('HARMONY$', 'HARMONY CENTER FOR REHABILITATION AND HEALING', newNameAlt)
            newNameAlt = re.sub('HAWTHORNE GLEN', 'HAWTHORN GLEN NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('HEARTLAND BUCYRUS', 'HEARTLAND OF BUCYRUS', newNameAlt)
            newNameAlt = re.sub('HENNIS CARE CENTRE DOVER', 'HENNIS CARE CENTRE OF DOVER', newNameAlt)
            newNameAlt = re.sub('HERITAGE CENTER', 'HERITAGE CENTER FOR REHABILITATION AND SPECIALITY CARE', newNameAlt)
            newNameAlt = re.sub('HERITAGE CORNER HEALTH CARE', 'HERITAGE CORNER NURSING HOME', newNameAlt)
            newNameAlt = re.sub('HERITAGESPRING', 'HERITAGESPRING HEALTHCARE CENTER OF WEST CHESTER', newNameAlt)
            newNameAlt = re.sub('HIGHLAND POINTE HEALTH REHABILITATION', 'HIGHLAND POINTE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('HILLEBRAND NURSING AND REHABILITATION', 'HILLEBRAND NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('HILLSPRING OF SPRINGBORO', 'HILLSPRING HEALTH CARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('HOSPITALITY CENTER', 'HOSPITALITY CENTER FOR REHABILITATION AND HEALING', newNameAlt)
            newNameAlt = re.sub('HUNTINGTON WOODS', 'HUNTINGTON WOODS CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('IVY WOODS MANOR', 'IVY WOODS HEALTHCARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('JACKSON RIDGE REHABILITATION AND CARE', 'JACKSON RIDGE REHABILITATION AND CARE CENTER', newNameAlt)
            newNameAlt = re.sub('JOSHUA TREE', 'JOSHUA TREE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('KENT HEALTHCARE CENTER', 'KENT HEALTHCARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('KENTON NURSING REHABILITATION CENTER', 'KENTON NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('KEYSTONE POINTE', 'KEYSTONE POINTE HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('LAFAYETTE POINTE', 'LAFAYETTE POINTE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LAKE POINTE REHABILITATION AND NURSING', 'LAKE POINTE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('LAKERIDGE ACRES', 'LAKERIDGE VILLA HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('LAKES OF MONCLOVA', 'LAKES OF MONCLOVA HEALTH CAMPUS', newNameAlt)
            newNameAlt = re.sub('LANDERBROOK', 'LANDERBROOK TRANSITIONAL CARE', newNameAlt)
            newNameAlt = re.sub('LAUREL\'S OF DEFIANCE', 'LAURELS OF DEFIANCE', newNameAlt)
            newNameAlt = re.sub('LEGENDS CARE CENTER', 'LEGENDS CARE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('LIFECARE CENTER OF ELYRIA', 'LIFE CARE CENTER OF ELYRIA', newNameAlt)
            newNameAlt = re.sub('LIFECARE WESTLAKE', 'LIFE CARE CENTER OF WESTLAKE', newNameAlt)
            newNameAlt = re.sub('LOCUST RIDGE', 'LOCUST RIDGE HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('LOGAN ELM HEALTH CARE', 'LOGAN ELM HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('LONDON HEALTH AND REHABILITATION', 'LONDON HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LOST CREEK HEALTHCARE AND REHABILITATION CENTER', 'LOST CREEK HEALTH CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LOVELAND HEALTH CARE', 'LOVELAND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MADEIRA CARE CENTER', 'MADEIRA HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MANOR CARE PARMA', 'MANOR CARE HEALTH SERVICES - PARMA', newNameAlt)
            newNameAlt = re.sub('MAPLE HILLS NURSING AND REHABILITATION', 'MAPLE HILLS SKILLED NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('MARJORIE P LEE', 'MARJORIE P LEE RETIREMENT COMMUNITY', newNameAlt)
            newNameAlt = re.sub('MASTERNICK MEMORIAL', 'MASTERNICK MEMORIAL HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MEADOW GROVE', 'MEADOW GROVE TRANSITIONAL CARE', newNameAlt)
            newNameAlt = re.sub('MENORAH PARK', 'MENORAH PARK CENTER FOR SENIOR', newNameAlt)
            newNameAlt = re.sub('MOHUN HEALTHCARE CENTER', 'MOHUN HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MONARCH MEADOWS', 'MONARCH MEADOWS NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('MONTEFIORE', 'MONTEFIORE HOME', newNameAlt)
            newNameAlt = re.sub('MOUNT ST JOSEPH', 'MOUNT SAINT JOSEPH REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('MT WASHINGTON CARE CENTER', 'MOUNT WASHINGTON CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MT AIRY GARDENS', 'MT AIRY GARDENS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('N OLMSTED HC LENNOX RIDGE', 'NORTH OLMSTED HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('NATIONAL CHURCH RESIDENCES$', 'NATIONAL CHURCH RESIDENCES CHILLICOTHE', newNameAlt)
            newNameAlt = re.sub('NORMANDY CARE', 'NORMANDY MANOR OF ROCKY RIVER', newNameAlt)
            newNameAlt = re.sub('NORTHCREST- LTC', 'NORTHCREST REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('OAK PAVILION', 'OAK PAVILION NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('OAK POINTE', 'OAK POINTE NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('OHIO LIVING$', 'OHIO LIVING DOROTHY LOVE', newNameAlt)
            newNameAlt = re.sub('OHIO LIVING MT PLEASANT', 'OHIO LIVING MOUNT PLEASANT', newNameAlt)
            newNameAlt = re.sub('OHIO VALLEY MANOR', 'OHIO VALLEY MANOR NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('OTTERBEIN NEW ALBANY SENIORLIFE NEIGHBORHOOD', 'OTTERBEIN NEW ALBANY', newNameAlt)
            newNameAlt = re.sub('OTTERBEIN-BATAVIA', 'OTTERBEIN BATAVIA', newNameAlt)
            newNameAlt = re.sub('OTTERBEIN-LOVELAND', 'OTTERBEIN LOVELAND', newNameAlt)
            newNameAlt = re.sub('OXFORD HEALTHCARE', 'OXFORD HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('PARK CENTER', 'PARK CENTER HEALTH CARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('PARK HEALTH', 'PARK HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('PARK TERRACE NURSING AND REHABILITATION', 'PARK TERRACE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('PARK VISTA', 'PARK VISTA NURSING AND REHABILITATION BY MCARE HEALTH', newNameAlt)
            newNameAlt = re.sub('PARKSIDE', 'PARKSIDE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('PARKVUE', 'PARKVUE HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('PARMACARE', 'PARMA CARE CENTER', newNameAlt)
            newNameAlt = re.sub('PICKAWAY MANOR', 'PICKAWAY MANOR CARE CENTER', newNameAlt)
            newNameAlt = re.sub('PINE RIDGE', 'PINE RIDGE SKILLED NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('PLEASANT VIEW LTC', 'PLEASANTVIEW CARE CENTER', newNameAlt)
            newNameAlt = re.sub('PRESIDENTIAL', 'PRESIDENTIAL POST-ACUTE', newNameAlt)
            newNameAlt = re.sub('PRESTIGE GARDENS', 'PRESTIGE GARDENS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('QUAKER HEIGHTS', 'QUAKER HEIGHTS NURSING HOME', newNameAlt)
            newNameAlt = re.sub('RICHMOND HTS PLACE', 'RICHMOND HEIGHTS PLACE-A CONTINUUM OF CARE COMMUNITY', newNameAlt)
            newNameAlt = re.sub('ROCKY RIVER GARDENS', 'ROCKY RIVER GARDENS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('ROLLING HILLS', 'ROLLING HILLS REHABILITATION AND CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SALEM NORTH', 'SALEM NORTH HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('SALEM WEST', 'SALEM WEST HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('SAMARITAN$', 'SAMARITAN CARE CENTER AND VILLA', newNameAlt)
            newNameAlt = re.sub('SANCTUARY POINTE', 'SANCTUARY POINTE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SCARLET OAKS NURSING AND REHABILITATION', 'SCARLET OAKS NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SCENIC POINTE', 'SCENIC POINTE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SEVEN HILLS HEALTH AND REHABILITATION', 'SEVEN HILLS HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SHADY LAWN', 'SHADY LAWN NURSING HOME', newNameAlt)
            newNameAlt = re.sub('SHAKER GARDENS', 'SHAKER GARDENS NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SHEPHERD OF THE VALLEY LIBERTY-FORMERLY NILES', 'SHEPHERD OF THE VALLEY LIBERTY', newNameAlt)
            newNameAlt = re.sub('SIENA GARDENS REHABILITATION', 'SIENA GARDENS REHABILITATION AND TRANSITIONAL CARE', newNameAlt)
            newNameAlt = re.sub('SKLD BRYAN', 'SKLD BRYAN ILLUMINATE HEALTH CARE BRYAN', newNameAlt)
            newNameAlt = re.sub('SKLD DEFIANCE', 'SKLD DEFIANCE ILLUMINATE HEALTH CARE DEFIANCE', newNameAlt)
            newNameAlt = re.sub('SKLD NEW LEBANON', 'SKLD NEW LEBANON ILLUMINATE HEALTH CARE NEW LEBANON', newNameAlt)
            newNameAlt = re.sub('SKLD NEW LEXINGTON', 'SKLD NEW LEXINGTON ILLUMINATE HEALTH CARE NEW LEXINGTON', newNameAlt)
            newNameAlt = re.sub('SKLD PERRYSBURG', 'SKLD PERRYSBURG ILLUMINATE HEALTH CARE PERRYSBURG', newNameAlt)
            newNameAlt = re.sub('SOLON POINTE', 'SOLON POINTE AT EMERALD RIDGE', newNameAlt)
            newNameAlt = re.sub('SOUTHERN HILLS', 'SOUTHERN HILLS HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('SPRING MEADOWS A VILLA CENTER', 'SPRING MEADOWS NURSING AND REHABILITATION CENTRE', newNameAlt)
            newNameAlt = re.sub('SPRINGMEADE', 'SPRINGMEADE HEALTHCENTER', newNameAlt)
            newNameAlt = re.sub('ST CATHERINE\'S FINDLAY', 'ST CATHERINE\'S MANOR OF FINDLAY', newNameAlt)
            newNameAlt = re.sub('ST FRANCIS', 'ST FRANCIS SENIOR MINISTRIES', newNameAlt)
            newNameAlt = re.sub('ST LEONARD', 'ST LEONARD HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SUNRISE POINT AT MAPLE HEIGHTS', 'SUNRISE POINTE NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('SUNSET VILLAGE-SYLVANIA CAMPUS', 'SUNSET VILLAGE - SYLVANIA CAMPUS', newNameAlt)
            newNameAlt = re.sub('SYCAMORE RUN', 'SYCAMORE RUN NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('TERRACE VIEW GARDENS', 'TERRACE VIEW GARDEN', newNameAlt)
            newNameAlt = re.sub('THE GREENS', 'THE GREENS CARE AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('THE LAURELS AT CHAGRIN FALLS', 'THE LAURELS OF CHAGRIN FALLS', newNameAlt)
            newNameAlt = re.sub('THE MEADOWS AT OSBORNE', 'THE MEADOWS AT OSBORN PARK', newNameAlt)
            newNameAlt = re.sub('TWILIGHT GARDENS AND REHABILITATION', 'TWILIGHT GARDENS NURSING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('UNIVERSITY MANOR', 'UNIVERSITY MANOR HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('VALLEY VIEW CARE CENTER', 'VALLEY VIEW ALZHEIMER\'S CARE CENTER', newNameAlt)
            newNameAlt = re.sub('VAN CREST LTC', 'VANCREST HEALTH CARE CENTER OF HOLGATE', newNameAlt)
            newNameAlt = re.sub('VANCREST$', 'VANCREST OF ST MARY\'S', newNameAlt)
            newNameAlt = re.sub('VANCREST HEALTHCARE CENTER', 'VANCREST HEALTH CARE CENTER OF EATON', newNameAlt)
            newNameAlt = re.sub('VERANDA GARDENS', 'VERANDA GARDENS AND ASSISTED LIVING', newNameAlt)
            newNameAlt = re.sub('VERSAILLES REHABILITATION AND HEALTHCARE CENTER', 'VERSAILLES REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('VILLA GEORGETOWN', 'VILLA GEORGETOWN REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('VILLA SPRINGFIELD', 'VILLA SPRINGFIELD REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('VILLAGE GREEN', 'VILLAGE GREEN HEALTH CAMPUS', newNameAlt)
            newNameAlt = re.sub('WALNUT CREEK', 'WALNUT CREEK NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('WALNUT HILLS', 'WALNUT HILLS NURSING HOME', newNameAlt)
            newNameAlt = re.sub('WALTON MANOR', 'WALTON MANOR HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('WASHINGTON SQUARE', 'WASHINGTON SQUARE HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('WILLOW RIDGE', 'WILLOW RIDGE OF MENNONITE HOME COMMUNITIES OF OHIO', newNameAlt)
            newNameAlt = re.sub('WILLOWOOD', 'WILLOWOOD CARE CENTER OF BRUNSWICK', newNameAlt)
            newNameAlt = re.sub('WINDSOR HOUSE - DOYLESTOWN', 'WINDSOR HOUSE AT DOYLESTOWN', newNameAlt)
            newNameAlt = re.sub('WINDSOR LANE HEALTH CARE', 'WINDSOR LANE HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('WOOD HAVEN HEALTH CARE', 'WOOD HAVEN HEALTH CARE SENIOR LIVING AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('WOODLANDS$', 'WOODLANDS HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('WOODRIDGE', 'WOODRIDGE HEALTHCARE', newNameAlt)
            newNameAlt = re.sub('WRIGHT REHABILITATION', 'WRIGHT REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('WYANDOT COUNTY SKILLED NURSING', 'WYANDOT COUNTY SKILLED NURSING AND REHABILITATION', newNameAlt)
            
            # OR
            """newNameAlt = re.sub('DALLAS RETIREMENT VILLAGE', 'DALLAS RETIREMENT VILLAGE HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('FRENCH PRAIRIE NURSING AND REHABILITATION', 'FRENCH PRAIRIE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LIFE CARE REHABILITATION', 'LIFE CARE CENTER OF MCMINNVILLE', newNameAlt)
            newNameAlt = re.sub('MARQUIS CENTENNIAL', 'MARQUIS CENTENNIAL POST ACUTE REHABILITATION', newNameAlt)
            newNameAlt = re.sub('PRESTIGE CARE MILWAUKIE', 'PRESTIGE POST-ACUTE AND REHABILITATION CENTER - MILWAUKIE', newNameAlt)
            newNameAlt = re.sub('REGENCY HERMISTON', 'REGENCY HERMISTON NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('REGENCY REDMOND', 'REGENCY REDMOND REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('REGENCY VILLAGE PRINEVILLE', 'REGENCY PRINEVILLE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('ROSE VILLA', 'ROSE VILLA SENIOR LIVING COMMUNITY', newNameAlt)
            newNameAlt = re.sub('WINDSOR HEALTH AND REHABILITATION', 'WINDSOR HEALTH AND REHABILITATION CENTER', newNameAlt)"""
            

            # PA
            # PASSAVANT RET AND HEALTH CENTER
            # PATRIOT, A CHOICE COMMUNITY THE
            """newNameAlt = re.sub('WILLOWBROOKE COURTSKILLEDCARECENTER AT NORMANDYFARMS ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT NORMANDY FARMS ESTATES', newNameAlt)
            newNameAlt = re.sub('WILLOWBROOKE COURTSKILLEDCARECENTER AT FORT WASHINGTON ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT FORT WASHINGTON ESTATES', newNameAlt)
            newNameAlt = re.sub(', T$', '', newNameAlt)
            newNameAlt = re.sub('SUSQUE- VIEW HOME', 'SUSQUE - VIEW HOME', newNameAlt)
            newNameAlt = re.sub('ROUSE- WARREN COUNTY HOME', 'ROUSE - WARREN COUNTY HOME', newNameAlt)
            newNameAlt = re.sub('QUALITY LIFE SERVICES APOLLO', 'QUALITY LIFE SERVICES - APOLLO', newNameAlt)
            newNameAlt = re.sub('QUALITY LIFE SERVICES GROVE CITY', 'QUALITY LIFE SERVICES - GROVE CITY', newNameAlt)
            newNameAlt = re.sub('QUALITY LIFE SERVICES MERCER', 'QUALITY LIFE SERVICES - MERCER', newNameAlt)
            newNameAlt = re.sub('ALLIED SERVICES CENTER CITY SKILLED NURISNG', 'ALLIED SERVICES CENTER CITY SKILLED NURSING', newNameAlt)
            newNameAlt = re.sub('BLOOMSBURG CARE AND REHABILITATION CENTER', 'BLOOMSBURG CARE CENTER AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('BRIARLEAF NURSING AND CONV CENTER', 'BRIARLEAF NURSING AND CONVALESCENT CENTER', newNameAlt)
            newNameAlt = re.sub('CLAREMONT NURSING AND REHABIL CENTER OF CUMBERLAND CO', 'CLAREMONT NURSING AND REHABIL CENTER OF CUMBERLAND COUNTY', newNameAlt)
            newNameAlt = re.sub('GOOD SHEPHERD HOME- BETHLEHEM', 'GOOD SHEPHERD HOME - BETHLEHEM', newNameAlt)
            newNameAlt = re.sub('GREENLEAF NURSING AND CONV CENTER', 'GREENLEAF NURSING AND CONVALESCENT CENTER', newNameAlt)
            newNameAlt = re.sub('HARMARVILLAGE CARE CENTER', 'HARMAR VILLAGE CARE CENTER', newNameAlt)
            newNameAlt = re.sub('JEWISH HOME OF EASTERN PA', 'JEWISH HOME OF EASTERN PENNSYLVANIA', newNameAlt)
            newNameAlt = re.sub('JUNIPER VILLAGE AT BUCKS COUNTY REHABILITATION AND SKILLED C', 'JUNIPER VILLAGE AT BUCKS COUNTY REHABILITATION AND SKILLED CARE', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES - WALLINGFORD', 'MANORCARE HEALTH SERVICES-WALLINGFORD', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-WMSPT NORTH', 'MANORCARE HEALTH SERVICES-WILLIAMSPORT NORTH', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-WMSPT SOUTH', 'MANORCARE HEALTH SERVICES-WILLIAMSPORT SOUTH', newNameAlt)
            newNameAlt = re.sub('PASSAVANT RET AND HEALTH CENTER', 'PASSAVANT RETIREMENT AND HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('RMH-HB/SNF', 'RIDDLE MEMORIAL HOSPITAL HB SNF', newNameAlt)
            newNameAlt = re.sub('SKILLED NURSING UNIT, ARMSTRONG CO MEMORIAL HOSPITAL', 'SKILLED NURSING UNIT, ARMSTRONG COUNTY MEMORIAL HOSPITAL', newNameAlt)
            newNameAlt = re.sub('SMITH HEALTH CARE, LTD.', 'SMITH HEALTH CARE', newNameAlt)
            newNameAlt = re.sub('THE PINES AT PHILADELPHIA REHABILITATIONANDHEALTHCARE CENTER', 'THE PINES AT PHILADELPHIA REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('WESBURY UNITED METHODIST COMM', 'WESBURY UNITED METHODIST COMMUNITY', newNameAlt)
            newNameAlt = re.sub('WESLEY ENHANCED LIVING MAIN LINE REHABILITATION AND SKD NURSING', 'WESLEY ENHANCED LIVING MAIN LINE REHABILITATION AND SKILLED NURSING', newNameAlt)
            newNameAlt = re.sub('WILLOWBROOKE COURT SKILLEDCARECENTER AT FORT WASHINGTON ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT FORT WASHINGTON ESTATES', newNameAlt)
            newNameAlt = re.sub('WILLOWBROOKE COURT SKILLED CARE CENTER AT BRITTANY POINTE ES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT BRITTANY POINTE ESTATES', newNameAlt)
            newNameAlt = re.sub('WILLOWS OF PRESBYTERIAN SENIORCARE', 'WILLOWS OF PRESBYTERIAN SENIOR CARE', newNameAlt)"""

            # RI
            # this is to strip the '(locality)' appended to each facility list name string
            """newNameAltSplit = newNameAlt.split('(')
            newNameAlt = newNameAltSplit[0]"""

            # TX

            # UT
            

            # VA
            # WOODS COVE (FRMLY ROYAL HAVEN OF FRONT ROYAL)
            # SKYVIEW SPRINGS NURSING HOME (FRMLY MONTVUE)
            # PARAMOUNT SENIOR LIVING (FRMLY BROOKDATE ALF)
            # BROOKSIDE REHABILITATION AND NURSING CENTER (OAK SPRINGS)
            """newNameAlt = re.sub('WALTER REED CONVALESCENT CENTER- GLOUCESTER', 'WALTER REED CONVALESCENT CENTER - GLOUCESTER', newNameAlt)
            newNameAlt = re.sub('SITTER-BARFOOT VETERANS CARE CENTER', 'SITTER - BARFOOT VETERANS CARE CENTER', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES- IMPERIAL', 'MANORCARE HEALTH SERVICES - IMPERIAL', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-ALEXANDRIA', 'MANORCARE HEALTH SERVICES - ALEXANDRIA', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-FAIR OAKS', 'MANORCARE HEALTH SERVICES - FAIR OAKS', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-RICHMOND', 'MANORCARE HEALTH SERVICES - RICHMOND', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS HEALTH AND REHABILITATION', 'ACCORDIUS HEALTH AT EMPORIA', newNameAlt)
            newNameAlt = re.sub('Waverly Health and Rehabilitation Center', 'ACCORDIUS HEALTH AT WAVERLY', newNameAlt)
            newNameAlt = re.sub('AUTUM CARE OF CHESAPEAKE', 'AUTUMN CARE OF CHESAPEAKE', newNameAlt)
            newNameAlt = re.sub('AUTUMN NURSING CARE', 'AUTUMN CARE OF SUFFOLK', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS BAY POINTE', 'ACCORDIUS HEALTH AT BAY POINTE', newNameAlt)
            newNameAlt = re.sub('ACCORDIUS HEALTH AND REHAB', 'ACCORDIUS HEALTH AT EMPORIA', newNameAlt)
            newNameAlt = re.sub('APPOMATTOX HEALTH AND REHABILITATION', 'APPOMATTOX HEALTH AND REHABILITATON CENTER', newNameAlt)
            # newNameAlt = re.sub('ACCORDIUS HEALTH AT WAYNESBORO \\(FRMLY CURIS\\)', 'ACCORDIUS HEALTH AT WAYNESBORO', newNameAlt)
            newNameAlt = re.sub('AUTUM CARE OF CHESAPEAKE', 'AUTUMN CARE OF CHESAPEAKE', newNameAlt)
            newNameAlt = re.sub('AUTUMN NURSING CARE', 'AUTUMN CARE OF SUFFOLK', newNameAlt)
            newNameAlt = re.sub('BETH SHALOM HOME OF EASTERN VIRGINIA', 'BETH SHOLOM HOME OF EASTERN VIRGINIA', newNameAlt)
            # newNameAlt = re.sub('BLUE RIDGE NURSING CENTER \(STUART\)', 'BLUE RIDGE THERAPY CONNECTION', newNameAlt)
            newNameAlt = re.sub('BLAND COUNTY NURSING AND REHABILITATION', 'BLAND COUNTY NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('BON SECOURS/MARYVIEW NURSING CENTER', 'BON SECOURS MARYVIEW NURSING CARE CENTER', newNameAlt)
            newNameAlt = re.sub('BRANDERMILL WOODS', 'THE HAVEN AT BRANDERMILL WOODS', newNameAlt)
            newNameAlt = re.sub('BRIDGEWATER RETIREMENT COMMUNITY-NH', 'BRIDGEWATER RETIREMENT COMMUNITY', newNameAlt)
            newNameAlt = re.sub('BROOKSIDE REHABILITATION AND NURSING CENTER \(OAK SPRINGS\)', 'BROOKSIDE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('BURKE HEALTH CARE CENTER', 'BURKE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CANTERBURY HEALTH AND REHABILITATION', 'CANTERBURY REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('CARRIAGE HILL HEALTH AND REHABILITATION','CARRIAGE HILL HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CARRINGTON PLACE AT BOTETOURT', 'CARRINGTON PLACE AT BOTETOURT COMMONS', newNameAlt)
            newNameAlt = re.sub('CHARLOTTESVILLE HEALTH AND REHAB CENTER', 'CHARLOTTESVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CHASE CITY HEALTH AND REHAB CENTER', 'CHASE CITY HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CHERRYDALE HEALTH & REHABILITATION CENTER', 'CHERRYDALE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('CHESAPEAKE HEALTH AND REHAB CENTER', 'CHESAPEAKE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('COLISEUM PARK CONV AND REHABILITATION CENTER', 'COLISEUM CONVALESCENT AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('COLONIAL HEIGHTS HEALTH CARE CENTER','COLONIAL HEIGHTS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('DULLES HEALTH AND REHABILITATION', 'DULLES HEALTH AND REHABILITATION CENTER', newNameAlt)
            # newNameAlt = re.sub('GAINESVILLE HEALTH AND REHABILITATION','GAINESVILLE HEALTH AND REHAB CENTER', newNameAlt)
            newNameAlt = re.sub('GALAX HEALTH AND REHABILITATION','GALAX HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('GLENBURNIE NURSING & REHAB', 'GLENBURNIE REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('CULPEPER HEALTH AND REHABILITATION','CULPEPER HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('DINWIDDIE HEALTH AND REHAB CENTER','DINWIDDIE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('DOGWOOD VILLAGE OF ORANGE COUNTY', 'DOGWOOD VILLAGE OF ORANGE COUNTY HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('DOCKSIDE HEALTH & REHABILITATION CENTER','DOCKSIDE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('DULLES HEALTH & REHAB', 'DULLES HEALTH AND REHAB CENTER', newNameAlt)
            newNameAlt = re.sub('FAIRFAX NURSING AND REHABILITATION CENTER', 'FAIRFAX REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('FAIRMONT CROSSING REHABILITATION AND HEALTHCARE', 'FAIRMONT CROSSING HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('FARMVILLE HEALTH AND REHAB CENTER','FARMVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('FREDERICKSBURG HEALTH AND REHABILITATION \(FRMLY GOLDEN LIVING\)','FREDERICKSBURG HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('GRACE HEALTH AND REHAB CENTER OF GREENE COUNTY','GRACE HEALTH AND REHABILITATION CENTER OF GREENE COUNTY', newNameAlt)
            newNameAlt = re.sub('GRAYSON NURSING AND REHABILITATION CENTER','GRAYSON REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('GREENSPRING VILLAGE ASSISTED LIVING','GREENSPRING', newNameAlt)
            newNameAlt = re.sub('EMPORIA/GREENSVILLE MANOR', 'GREENSVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('HANOVER HEALTHCARE','HANOVER HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('HEARTLAND HEALTH CARE CENTER', 'HEARTLAND HEALTH CARE CENTER - LYNCHBURG', newNameAlt)
            newNameAlt = re.sub('HERITAGE HALL NURSING AND REHABILITATION', 'HERITAGE HALL - LEESBURG', newNameAlt)
            newNameAlt = re.sub('HERITAGE HALL NURSING HOME', 'HERITAGE HALL - BLACKSTONE', newNameAlt)
            newNameAlt = re.sub('HILLSVILLE HEALTH AND REHABILITATION', 'HILLSVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('HUNDLEY CENTER LTCF', 'VCU HEALTH CMH HUNDLEY CENTER', newNameAlt)
            newNameAlt = re.sub('KEMPSVILLE HEALTH & REHAB', 'KEMPSVILLE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('KING\'S DAUGHTERS\' COMM HEALTH AND REHAB CENTER', 'KINGS DAUGHTERS COMMUNITY HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LAKE MANASSAS HEALTH AND REHABILITATION', 'LAKE MANASSAS HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LAKEWOOD MANOR BAPTIST RETIREMENT COMMUNITY', 'LAKEWOOD', newNameAlt)
            newNameAlt = re.sub('LEE HEALTH AND REHABILITATION', 'LEE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LIBERTY RIDGE HEALTH AND REHABILITATION', 'LIBERTY RIDGE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LOUISA HEALTH & REHABILITATION CENTER','LOUISA HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('LYNN CARE CENTER', 'WARREN MEMORIAL HOSPITAL LYNN CARE', newNameAlt)
            newNameAlt = re.sub('LUCY CORR VILLAGE', 'HEALTH CARE CENTER LUCY CORR', newNameAlt)
            newNameAlt = re.sub('MANASSAS HEALTH & REHABILITATION CENTER', 'MANASSAS HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('MANOR CARE HEALTH SERVICES - ARLINGTON', 'MANORCARE HEALTH SERVICES - ARLINGTON', newNameAlt)
            newNameAlt = re.sub('MANOR CARE HEALTH SERVICES- IMPERIAL', 'MANORCARE HEALTH SERVICES - IMPERIAL', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-ALEXANDRIA', 'MANORCARE HEALTH SERVICES - ALEXANDRIA', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-FAIR OAKS', 'MANORCARE HEALTH SERVICES - FAIR OAKS', newNameAlt)
            newNameAlt = re.sub('MANORCARE HEALTH SERVICES-RICHMOND', 'MANORCARE HEALTH SERVICES - RICHMOND', newNameAlt)
            newNameAlt = re.sub('MONROE HEALTH & REHABILITATION CENTER','MONROE HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('MOUNT VERNON NURSING AND REHABILITATION CENTER', 'MOUNT VERNON HEALTHCARE CENTER', newNameAlt)
            newNameAlt = re.sub('MULBERRY CREEK NURSING AND REHABILITATION', 'MULBERRY CREEK NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('NANSEMOND POINTE REHABILITATION', 'ACCORDIUS HEALTH AT NANSEMOND POINTE', newNameAlt)
            newNameAlt = re.sub('NHC HEALTHCARE', 'NHC HEALTHCARE BRISTOL', newNameAlt)
            newNameAlt = re.sub('NORFOLK HEALTH AND REHAB CENTER','NORFOLK HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('NORTHAMPTON CONVALESCENT & REHABILITATION CENTER','NORTHAMPTON CONVALESCENT AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('OAKWOOD HEALTH AND REHAB CENTER','OAKWOOD HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('OUR LADY OF HOPE','OUR LADY OF HOPE HEALTH CENTER', newNameAlt)
            newNameAlt = re.sub('PELICAN HEALTH CARE','PELICAN HEALTH NORFOLK', newNameAlt)
            newNameAlt = re.sub('PORTSIDE HEALTH AND REHABILITATION','PORTSIDE HEALTH AND REHAB CENTER', newNameAlt)
            newNameAlt = re.sub('RALEIGH COURT HEALTHCARE FACILITY','RALEIGH COURT HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('REGENCY HEALTHCARE CENTER','REGENCY HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('REHAB CENTER AND MEMORY CARE OF BRISTOL', 'THE REHAB CENTER AT BRISTOL', newNameAlt)
            newNameAlt = re.sub('RIVER VIEW ON THE APPOMATTOX HEALTH AND REHABILITATON CENTER', 'RIVER VIEW ON THE APPOMATTOX HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('ROMAN EAGLE MEMORIAL HOME','ROMAN EAGLE REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SENTARA NURSING CENTER$','SENTARA NURSING CENTER - VIRGINIA BEACH', newNameAlt)
            newNameAlt = re.sub('SENTARA NURSING CENTER - CHESAPEAKE','SENTARA REHABILITATION AND CARE RESIDENCE - CHESAPEAKE', newNameAlt)
            newNameAlt = re.sub('SIGNATURE HEALTHCARE, LLC','SIGNATURE HEALTHCARE OF NORFOLK', newNameAlt)
            newNameAlt = re.sub('SITTER - BARFOOT VETERANS CARE CENTER','SITTER AND BARFOOT VETERANS CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SKYLINE MANOR NURSING AND REHAB CENTER','SKYLINE NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('SKYVIEW SPRINGS NURSING HOME \(FRMLY MONTVUE\)', 'SKYVIEW SPRINGS REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('STANLEYTOWN HEALTHCARE CENTER', 'STANLEYTOWN HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('THE CITADEL', 'THE CITADEL VIRGINIA BEACH', newNameAlt)
            newNameAlt = re.sub('THE GLEBE RETIREMENT COMMUNITY', 'THE GLEBE', newNameAlt)
            newNameAlt = re.sub('THE VIRGINIAN RETIREMENT COMMUNITY', 'THE VIRGINIAN', newNameAlt)
            newNameAlt = re.sub('VALLEY HEALTH CARE', 'VALLEY REHABILITATION AND NURSING CENTER', newNameAlt)
            newNameAlt = re.sub('VIRGINIA BEACH HEALTHCARE AND REHABILITATION', 'VIRGINIA BEACH HEALTHCARE AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('WADDELL NURSING AND REHABILITATION', 'WADDELL NURSING AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('WALTER REED CONVALESCENT CENTER- GLOUCESTER', 'WALTER REED CONVALESCENT AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('WELLSPRING AT AMELIA', 'WELLSPRINGS AT AMELIA', newNameAlt)
            newNameAlt = re.sub('WESTMINSTER CANTERBURY OF THE BLUE RIDGE NH', 'WESTMINSTER CANTERBURY OF THE BLUE RIDGE', newNameAlt)
            newNameAlt = re.sub('WOODMONT HEALTHCARE CENTER', 'WOODMONT CENTER', newNameAlt)
            newNameAlt = re.sub('WOODS COVE \(FRMLY ROYAL HAVEN OF FRONT ROYAL\)', 'WOODS COVE', newNameAlt)
            newNameAlt = re.sub('BROOKSIDE REHABILITATION AND NURSING CENTER (OAK SPRINGS)', 'BROOKSIDE REHABILITATION AND NURSING CENTER', newNameAlt)"""

            # WI
            """newNameAlt = re.sub('\*BENEDICTINE MANOR', 'BENEDICTINE MANOR', newNameAlt)
            newNameAlt = re.sub('\*LAKELAND HEALTH CARE CENTER', 'LAKELAND HEALTH CARE CENTER', newNameAlt)
            newNameAlt = re.sub('\*MANITOWOC HEALTH AND REHABILITATION CENTER', 'MANITOWOC HEALTH AND REHABILITATION CENTER', newNameAlt)
            newNameAlt = re.sub('\*MASONIC CENTER FOR HEALTH AND REHABILITATION', 'MASONIC CENTER FOR HEALTH AND REHABILITATION', newNameAlt)
            newNameAlt = re.sub('AUGUSTA HEALTH AND REHAILITATION', 'AUGUSTA HEALTH AND REHABILITATION', newNameAlt)"""



            # WV
            """newNameAlt = re.sub('NELLAS NURSING HOME', 'NELLA\'S NURSING HOME', newNameAlt)
            newNameAlt = re.sub('MONTGOMERY GENERAL HOSPITAL \(SKILLED NURSING\)', 'MONTGOMERY GENERAL HOSPITAL', newNameAlt)"""

            # WY
            """newNameAlt = re.sub('GOSHEN HEALTHCARE', 'GOSHEN HEALTHCARE COMMUNITY', newNameAlt)
            newNameAlt = re.sub('LIFECARE OF CASPER', 'LIFE CARE CENTER OF CASPER', newNameAlt)
            newNameAlt = re.sub('LIFECARE OF CHEYENNE', 'LIFE CARE CENTER OF CHEYENNE', newNameAlt)
            newNameAlt = re.sub('NEW HORIZAONS CARE CENTER', 'NEW HORIZONS CARE CENTER', newNameAlt)
            newNameAlt = re.sub('SHEPHERD OF THE VALLEY', 'SHEPHERD OF THE VALLEY REHABILITION AND WELLNESS', newNameAlt)"""



            print(newNameAlt)
            newNameAltStrip = newNameAlt.strip()
            row['Facility Name Normalized'] = newNameAltStrip
            csv_rows.append(row)

clean_cms_data(csv_input)

def output_clean_cms_data(csv_output, headers_facility_list, csv_rows):
    csv_output_file = csv_output + '.csv'
    with open(csv_output_file, 'w') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames = headers_facility_list)
        writer.writeheader()
        writer.writerows(csv_rows)

output_clean_cms_data(csv_output, headers_facility_list, csv_rows)