# -*- coding: utf-8 -*-
import re

def normalize_CA(newNameAlt):
      # print('passed in facility name: ', newNameAlt)

      # CA
      # newNameAlt = re.findall('\d|$', 'CRESTWOOD MANOR')[0]
      newNameAlt = re.sub('ADVENTIST HEALTH SONORA - D/P SNF \(UNIT 6\)', 'ADVENTIST HEALTH SONORA - D/P SNF', newNameAlt)
      newNameAlt = re.sub('ADVENTIST HEALTH SONORA - D/P SNF \(UNIT 7\)', 'ADVENTIST HEALTH SONORA - D/P SNF', newNameAlt)
      newNameAlt = re.sub('CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - PEDIATRIC HOSPI', 'CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - PEDIATRIC HOSPITAL', newNameAlt)
      newNameAlt = re.sub('CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - SARATOGA PEDIAT', 'CHILDREN\'S HEALTHCARE ORGANIZATION OF NORTHERN CALIFORNIA - SARATOGA PEDIATRIC HOSPITAL', newNameAlt)
      newNameAlt = re.sub('EASTERN PLUMAS HOSPITAL-PORTOLA CAMPUS D/P SNF', 'EASTERN PLUMAS HOSPITAL - PORTOLA CAMPUS D/P SNF', newNameAlt)
      newNameAlt = re.sub('MANCHESTER MANOR CVLT HOSPITAL', 'MANCHESTER MANOR CONVALESCENT HOSPITAL', newNameAlt)
      newNameAlt = re.sub('MARIAN REGIONAL MEDICAL CENTER DP/SNF', 'MARIAN MEDICAL CENTER D/P SNF', newNameAlt)
      newNameAlt = re.sub('MIRADA HILLS REHABILITATION AND CONVALESCENT HOSP', 'MIRADA HILLS REHABILITATION AND CONVALESCENT HOSPITAL', newNameAlt)
      newNameAlt = re.sub('PALM VILLAGE RETIREMENT COMMUNITY HEALTH CARE CENTER.', 'PALM VILLAGE RETIREMENT COMMUNITY HEALTH CARE CENTER', newNameAlt)
      newNameAlt = re.sub('SKYLINE HEALTHCARE CENTER-LOS ANGELES', 'SKYLINE HEALTHCARE CENTER - LOS ANGELES', newNameAlt)

      # print('moduled normalized new name alt: ', newNameAlt)

      return newNameAlt