# -*- coding: utf-8 -*-
import re

def normalize_NY(newNameAlt):
      # print('passed in facility name: ', newNameAlt)
      # NY
      newNameAlt = re.sub('BROOKLYN CENTER FOR REHABILITATION AND RESIDENTIAL', 'BROOKLYN CENTER FOR REHABILITATION AND RESIDENTIAL HEALTH CARE', newNameAlt)
      newNameAlt = re.sub('COMPREHENSIVE REHABILITATION AND NURSING CENTER AT', 'COMPREHENSIVE REHABILITATION AND NURSING CENTER AT WILLIAMSVILLE', newNameAlt)
      newNameAlt = re.sub('HAVEN MANOR HEALTH CARE CENTER,LLC', 'HAVEN MANOR HEALTH CARE CENTER', newNameAlt)
      newNameAlt = re.sub('HUDSON POINTE AT RIVERDALE CENTER FOR NURSING AND', 'HUDSON POINTE AT RIVERDALE CENTER FOR NURSING AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('KATHERINE LUTHER RESIDENTIAL HEALTH CARE AND', 'KATHERINE LUTHER RESIDENTIAL HEALTH CARE AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('NORTHWELL HEALTH STERN FAMILY CENTER FOR', 'NORTHWELL HEALTH STERN FAMILY CENTER FOR REHABILITATION', newNameAlt)
      newNameAlt = re.sub('RICHMOND CENTER FOR REHABILITATION AND SPECIALTY', 'RICHMOND CENTER FOR REHABILITATION AND SPECIALTY HEALTHCARE', newNameAlt)
      newNameAlt = re.sub('SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF', 'SAPPHIRE CENTER FOR REHABILITATION AND NURSING OF CENTRAL QUEENS', newNameAlt)
      newNameAlt = re.sub('SCHULMAN AND SCHACHNE INSTITUTE FOR NURSING AND', 'SCHULMAN AND SCHACHNE INSTITUTE FOR NURSING AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('SEA VIEW HOSPITAL, REHABILITATION CENTER AND HOME', 'SEA VIEW HOSPITAL REHABILITATION CENTER AND HOME', newNameAlt)
      newNameAlt = re.sub('SPLIT ROCK REHABILITION AND HEALTH CARE CENTER', 'SPLIT ROCK REHABILITATION AND HEALTH CARE CENTER', newNameAlt)
      newNameAlt = re.sub('THE BROOK AT HIGH FALLS NURSING HOME AND REHABILITATION', 'THE BROOK AT HIGH FALLS NURSING HOME AND REHABILITATION CENTER', newNameAlt)
      newNameAlt = re.sub('THE CHATEAU AT BROOKLYN REHABILITATION AND NURSING', 'THE CHATEAU AT BROOKLYN REHABILITATION AND NURSING CENTER', newNameAlt)
      newNameAlt = re.sub('THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING', 'THE COTTAGES AT GARDEN GROVE, A SKILLED NURSING COMMUNITY', newNameAlt)
      newNameAlt = re.sub('THE PARAMOUNT AT SOMERS REHABILITATION AND NURSING', 'THE PARAMOUNT AT SOMERS REHABILITATION AND NURSING CENTER', newNameAlt)
      newNameAlt = re.sub('THE PINES AT GLENS FALLS CENTER FOR NURSING  AND', 'THE PINES AT GLENS FALLS CENTER FOR NURSING AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('THE PINES AT POUGHKEEPSIE CENTER FOR NURSING  AND', 'THE PINES AT POUGHKEEPSIE CENTER FOR NURSING AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('THE VALLEY VIEW CENTER FOR NURSING CARE AND', 'THE VALLEY VIEW CENTER FOR NURSING CARE AND REHABILITATION', newNameAlt)
      newNameAlt = re.sub('THE WILLOWS AT RAMAPO REHABILITATION AND NURSING', 'THE WILLOWS AT RAMAPO REHABILITATION AND NURSING CENTER', newNameAlt)
      newNameAlt = re.sub('VILLAGECARE REHABILITATION AND NURSING CENTER', 'VILLAGE CARE REHABILITATION AND NURSING CENTER', newNameAlt)

      # print('moduled normalized new name alt: ', newNameAlt)

      return newNameAlt