# -*- coding: utf-8 -*-
import re

def normalize_PA(newNameAlt):
      # print('passed in facility name: ', newNameAlt)
      # PA
      # PASSAVANT RET AND HEALTH CENTER
      # PATRIOT, A CHOICE COMMUNITY THE
      newNameAlt = re.sub('WILLOWBROOKE COURTSKILLEDCARECENTER AT NORMANDYFARMS ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT NORMANDY FARMS ESTATES', newNameAlt)
      newNameAlt = re.sub('WILLOWBROOKE COURTSKILLEDCARECENTER AT FORT WASHINGTON ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT FORT WASHINGTON ESTATES', newNameAlt)
      newNameAlt = re.sub(', T$', '', newNameAlt)
      newNameAlt = re.sub('SUSQUE- VIEW HOME', 'SUSQUE - VIEW HOME', newNameAlt)
      newNameAlt = re.sub('ROUSE- WARREN COUNTY HOME', 'ROUSE - WARREN COUNTY HOME', newNameAlt)
      newNameAlt = re.sub('QUALITY LIFE SERVICES APOLLO', 'QUALITY LIFE SERVICES - APOLLO', newNameAlt)
      newNameAlt = re.sub('QUALITY LIFE SERVICES GROVE CITY', 'QUALITY LIFE SERVICES - GROVE CITY', newNameAlt)
      newNameAlt = re.sub('QUALITY LIFE SERVICES MERCER', 'QUALITY LIFE SERVICES - MERCER', newNameAlt)
      newNameAlt = re.sub('ALLIED SERVICES CENTER CITY SKILLED NURISNG', 'ALLIED SERVICES CENTER CITY SKILLED NURSING', newNameAlt)
      newNameAlt = re.sub('BLOOMSBURG CARE AND REHABILITATION CENTER', 'BLOOMSBURG CARE CENTER AND REHABILITATION CENTER', newNameAlt)
      newNameAlt = re.sub('BRIARLEAF NURSING AND CONV CENTER', 'BRIARLEAF NURSING AND CONVALESCENT CENTER', newNameAlt)
      newNameAlt = re.sub('CLAREMONT NURSING AND REHABIL CENTER OF CUMBERLAND CO', 'CLAREMONT NURSING AND REHABIL CENTER OF CUMBERLAND COUNTY', newNameAlt)
      newNameAlt = re.sub('GOOD SHEPHERD HOME- BETHLEHEM', 'GOOD SHEPHERD HOME - BETHLEHEM', newNameAlt)
      newNameAlt = re.sub('GREENLEAF NURSING AND CONV CENTER', 'GREENLEAF NURSING AND CONVALESCENT CENTER', newNameAlt)
      newNameAlt = re.sub('HARMARVILLAGE CARE CENTER', 'HARMAR VILLAGE CARE CENTER', newNameAlt)
      newNameAlt = re.sub('JEWISH HOME OF EASTERN PA', 'JEWISH HOME OF EASTERN PENNSYLVANIA', newNameAlt)
      newNameAlt = re.sub('JUNIPER VILLAGE AT BUCKS COUNTY REHABILITATION AND SKILLED C', 'JUNIPER VILLAGE AT BUCKS COUNTY REHABILITATION AND SKILLED CARE', newNameAlt)
      newNameAlt = re.sub('MANORCARE HEALTH SERVICES - WALLINGFORD', 'MANORCARE HEALTH SERVICES-WALLINGFORD', newNameAlt)
      newNameAlt = re.sub('MANORCARE HEALTH SERVICES-WMSPT NORTH', 'MANORCARE HEALTH SERVICES-WILLIAMSPORT NORTH', newNameAlt)
      newNameAlt = re.sub('MANORCARE HEALTH SERVICES-WMSPT SOUTH', 'MANORCARE HEALTH SERVICES-WILLIAMSPORT SOUTH', newNameAlt)
      newNameAlt = re.sub('PASSAVANT RET AND HEALTH CENTER', 'PASSAVANT RETIREMENT AND HEALTH CENTER', newNameAlt)
      newNameAlt = re.sub('RMH-HB/SNF', 'RIDDLE MEMORIAL HOSPITAL HB SNF', newNameAlt)
      newNameAlt = re.sub('SKILLED NURSING UNIT, ARMSTRONG CO MEMORIAL HOSPITAL', 'SKILLED NURSING UNIT, ARMSTRONG COUNTY MEMORIAL HOSPITAL', newNameAlt)
      newNameAlt = re.sub('SMITH HEALTH CARE, LTD.', 'SMITH HEALTH CARE', newNameAlt)
      newNameAlt = re.sub('THE PINES AT PHILADELPHIA REHABILITATIONANDHEALTHCARE CENTER', 'THE PINES AT PHILADELPHIA REHABILITATION AND HEALTHCARE CENTER', newNameAlt)
      newNameAlt = re.sub('WESBURY UNITED METHODIST COMM', 'WESBURY UNITED METHODIST COMMUNITY', newNameAlt)
      newNameAlt = re.sub('WESLEY ENHANCED LIVING MAIN LINE REHABILITATION AND SKD NURSING', 'WESLEY ENHANCED LIVING MAIN LINE REHABILITATION AND SKILLED NURSING', newNameAlt)
      newNameAlt = re.sub('WILLOWBROOKE COURT SKILLEDCARECENTER AT FORT WASHINGTON ESTATES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT FORT WASHINGTON ESTATES', newNameAlt)
      newNameAlt = re.sub('WILLOWBROOKE COURT SKILLED CARE CENTER AT BRITTANY POINTE ES', 'WILLOWBROOKE COURT SKILLED CARE CENTER AT BRITTANY POINTE ESTATES', newNameAlt)
      newNameAlt = re.sub('WILLOWS OF PRESBYTERIAN SENIORCARE', 'WILLOWS OF PRESBYTERIAN SENIOR CARE', newNameAlt)

      # print('moduled normalized new name alt: ', newNameAlt)

      return newNameAlt